version: '3.4'

volumes:
  mongodb-keys:

services:
  mongodb-keys:
    image: depop/openssl-bats
    volumes:
      - mongodb-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: sensorr-database
    environment:
      - MONGO_INITDB_DATABASE=${NX_MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${NX_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${NX_MONGO_PASSWORD}
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - 27017:${NX_MONGO_PORT}
    volumes:
      - mongodb-keys:/opt/keyfile
      - ./docker/mongodb:/docker-entrypoint-initdb.d:ro
      - ./data/db:/data/db
    depends_on:
        - mongodb-keys
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 60s
      start_period: 30s
    command: ['--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/opt/keyfile/mongodb-keyfile']
