// The releases the demo indexer answers, made up from the name searched: the same search gives the same releases,
// in the demo data generated by `tools/demo/seed.ts` as in the page. Plain TypeScript without relative import, so
// Node runs it as it is

export const INDEXER = { name: 'Demo indexer', url: 'https://indexer.sensorr.demo/api', key: 'demo' }

const LANGUAGES = ['MULTi.VFF', 'MULTi.VF2', 'MULTi', 'TRUEFRENCH', 'FRENCH', 'VOSTFR', '']
const RESOLUTIONS = ['720p', '1080p', '1080p', '2160p']
const SOURCES = ['BluRay', 'WEB-DL', 'WEBRip', 'HDLight', 'REMUX']
const ENCODINGS: { [resolution: string]: string[] } = { '720p': ['x264'], '1080p': ['x264', 'x265'], '2160p': ['x265', 'HEVC'] }
const AUDIOS = ['AC3', 'EAC3', 'DTS', 'DTS-HD.MA', 'AAC', 'TrueHD.Atmos']
const GROUPS = ['DEMO', 'SPRNG', 'VCR', 'TAPE', 'REWiND', 'KINESCOPE']
// Bytes a minute of film weighs, by resolution, before the source and the encoding change it
const WEIGHTS: { [resolution: string]: number } = { '720p': 30e6, '1080p': 70e6, '2160p': 180e6 }

export type Search = { title: string, year?: number | string, runtime?: number, season?: number, episode?: number }

export type IndexerItem = {
  guid: string
  title: string
  link: string
  comments: string
  enclosure: string
  size: number
  seeders: number
  peers: number
  grabs: number
  publishDate: string
  category: number[]
}

const hash = (value: string) => [...value].reduce((acc, char) => (Math.imul(acc ^ char.charCodeAt(0), 16777619) >>> 0), 2166136261)

// Mulberry32: the same seed, the same sequence
const random = (seed: number) => () => {
  seed = (seed + 0x6D2B79F5) >>> 0
  let value = seed
  value = Math.imul(value ^ (value >>> 15), value | 1)
  value ^= value + Math.imul(value ^ (value >>> 7), value | 61)
  return ((value ^ (value >>> 14)) >>> 0) / 4294967296
}

const pick = <T>(next: () => number, values: T[]): T => values[Math.floor(next() * values.length)]

export const dotted = (title: string) => title
  .normalize('NFD').replace(/[̀-ͯ]/g, '')
  .replace(/['’:,!?()]/g, '')
  .replace(/&/g, 'and')
  .replace(/[^A-Za-z0-9]+/g, '.')
  .replace(/^\.|\.$/g, '')

const numbered = (season?: number, episode?: number) => [
  season === undefined ? '' : `S${String(season).padStart(2, '0')}`,
  episode === undefined ? '' : `E${String(episode).padStart(2, '0')}`,
].join('')

export const searchOf = (search: Search, now = Date.now()): IndexerItem[] => {
  const key = [search.title, search.year, search.season, search.episode].filter((part) => part !== undefined && part !== '').join('|').toLowerCase()
  const next = random(hash(key))
  const count = Math.floor(next() * 9)
  const minutes = search.episode !== undefined ? 50 : search.season !== undefined ? 50 * 8 : (search.runtime || 110)

  return Array.from({ length: count }, (_, index) => {
    const drawn = pick(next, RESOLUTIONS)
    const source = pick(next, SOURCES)
    const encoded = pick(next, ENCODINGS[drawn])
    // A remux is the disc untouched: no 720p, no encoder, the disc's own codec
    const remux = source === 'REMUX'
    const resolution = remux && drawn === '720p' ? '1080p' : drawn
    const encoding = remux ? (resolution === '2160p' ? 'HEVC' : 'AVC') : encoded
    const name = [
      dotted(search.title),
      search.season === undefined ? search.year : `${numbered(search.season, search.episode)}${search.episode === undefined ? '.COMPLETE' : ''}`,
      pick(next, LANGUAGES),
      resolution,
      remux ? 'BluRay.REMUX' : source,
      encoding,
      pick(next, AUDIOS),
    ].filter(Boolean).join('.')
    const title = `${name}-${pick(next, GROUPS)}`
    const factor = remux ? 3 : (source === 'HDLight' ? 0.4 : 1) * (['x265', 'HEVC'].includes(encoding) ? 0.6 : 1)
    const id = `${hash(`${key}#${index}`).toString(16)}${index}`
    const seeders = Math.floor(next() * 400)

    return {
      guid: `${INDEXER.url.replace(/\/api$/, '')}/torrents/${id}`,
      title,
      link: `${INDEXER.url.replace(/\/api$/, '')}/torrents/${id}`,
      comments: `${INDEXER.url.replace(/\/api$/, '')}/torrents/${id}#comments`,
      enclosure: `${INDEXER.url.replace(/\/api$/, '')}/dl/${id}.torrent`,
      size: Math.round(minutes * WEIGHTS[resolution] * factor * (0.85 + next() * 0.3)),
      seeders,
      peers: seeders + Math.floor(next() * 40),
      grabs: Math.floor(next() * 3000),
      publishDate: new Date(now - Math.floor(next() * 400) * 86400000).toISOString(),
      category: [search.season === undefined ? 2040 : 5040],
    }
  })
}
