import type { Seed } from '../server/store'

// The data a visitor starts from, generated by `tools/demo/seed.ts` into `seed.json`, which is not committed: the
// `demo` build copies it next to the page. The TMDB key is the demo's own, given at build time and never written in
// the repository
export const seedOf = async (tmdb: string): Promise<Seed> => {
  const res = await fetch(new URL('demo/seed.json', document.baseURI))

  if (!res.ok) {
    throw new Error(`[Demo] The demo data answered ${res.status}`)
  }

  const seed = await res.json()

  return {
    version: seed.version,
    collections: seed.collections,
    files: { 'config.json': JSON.stringify({ ...seed.config, tmdb }) },
  }
}
