import type { Seed } from '../server/store'

// The data a visitor starts from, generated by `tools/demo/seed.mjs` into `seed.json`. The TMDB key is the demo's
// own, given at build time and never written in the repository
export const seedOf = async (tmdb: string): Promise<Seed> => {
  const { default: seed } = await import(/* webpackChunkName: "demo-seed" */ './seed.json')

  return {
    version: seed.version,
    collections: seed.collections,
    files: { 'config.json': JSON.stringify({ ...seed.config, tmdb }) },
  }
}
