export const countries = {
  AD: {
    name: 'Andorra',
    native: 'Andorra',
    languages: ['ca'],
    emoji: '🇦🇩',
  },
  AE: {
    name: 'United Arab Emirates',
    native: 'دولة الإمارات العربية المتحدة',
    languages: ['ar'],
    emoji: '🇦🇪',
  },
  AF: {
    name: 'Afghanistan',
    native: 'افغانستان',
    languages: ['ps', 'uz', 'tk'],
    emoji: '🇦🇫',
  },
  AG: {
    name: 'Antigua and Barbuda',
    native: 'Antigua and Barbuda',
    languages: ['en'],
    emoji: '🇦🇬',
  },
  AI: {
    name: 'Anguilla',
    native: 'Anguilla',
    languages: ['en'],
    emoji: '🇦🇮',
  },
  AL: {
    name: 'Albania',
    native: 'Shqipëria',
    languages: ['sq'],
    emoji: '🇦🇱',
  },
  AM: {
    name: 'Armenia',
    native: 'Հայաստան',
    languages: ['hy', 'ru'],
    emoji: '🇦🇲',
  },
  AO: {
    name: 'Angola',
    native: 'Angola',
    languages: ['pt'],
    emoji: '🇦🇴',
  },
  AQ: {
    name: 'Antarctica',
    native: 'Antarctica',
    languages: [],
    emoji: '🇦🇶',
  },
  AR: {
    name: 'Argentina',
    native: 'Argentina',
    languages: ['es', 'gn'],
    emoji: '🇦🇷',
  },
  AS: {
    name: 'American Samoa',
    native: 'American Samoa',
    languages: ['en', 'sm'],
    emoji: '🇦🇸',
  },
  AT: {
    name: 'Austria',
    native: 'Österreich',
    languages: ['de'],
    emoji: '🇦🇹',
  },
  AU: {
    name: 'Australia',
    native: 'Australia',
    languages: ['en'],
    emoji: '🇦🇺',
  },
  AW: {
    name: 'Aruba',
    native: 'Aruba',
    languages: ['nl', 'pa'],
    emoji: '🇦🇼',
  },
  AX: {
    name: 'Aland',
    native: 'Åland',
    languages: ['sv'],
    emoji: '🇦🇽',
    partOf: 'FI',
  },
  AZ: {
    name: 'Azerbaijan',
    native: 'Azərbaycan',
    languages: ['az'],
    emoji: '🇦🇿',
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    native: 'Bosna i Hercegovina',
    languages: ['bs', 'hr', 'sr'],
    emoji: '🇧🇦',
  },
  BB: {
    name: 'Barbados',
    native: 'Barbados',
    languages: ['en'],
    emoji: '🇧🇧',
  },
  BD: {
    name: 'Bangladesh',
    native: 'Bangladesh',
    languages: ['bn'],
    emoji: '🇧🇩',
  },
  BE: {
    name: 'Belgium',
    native: 'België',
    languages: ['nl', 'fr', 'de'],
    emoji: '🇧🇪',
  },
  BF: {
    name: 'Burkina Faso',
    native: 'Burkina Faso',
    languages: ['fr', 'ff'],
    emoji: '🇧🇫',
  },
  BG: {
    name: 'Bulgaria',
    native: 'България',
    languages: ['bg'],
    emoji: '🇧🇬',
  },
  BH: {
    name: 'Bahrain',
    native: '‏البحرين',
    languages: ['ar'],
    emoji: '🇧🇭',
  },
  BI: {
    name: 'Burundi',
    native: 'Burundi',
    languages: ['fr', 'rn'],
    emoji: '🇧🇮',
  },
  BJ: {
    name: 'Benin',
    native: 'Bénin',
    languages: ['fr'],
    emoji: '🇧🇯',
  },
  BL: {
    name: 'Saint Barthelemy',
    native: 'Saint-Barthélemy',
    languages: ['fr'],
    emoji: '🇧🇱',
  },
  BM: {
    name: 'Bermuda',
    native: 'Bermuda',
    languages: ['en'],
    emoji: '🇧🇲',
  },
  BN: {
    name: 'Brunei',
    native: 'Negara Brunei Darussalam',
    languages: ['ms'],
    emoji: '🇧🇳',
  },
  BO: {
    name: 'Bolivia',
    native: 'Bolivia',
    languages: ['es', 'ay', 'qu'],
    emoji: '🇧🇴',
  },
  BQ: {
    name: 'Bonaire',
    native: 'Bonaire',
    languages: ['nl'],
    emoji: '🇧🇶',
  },
  BR: {
    name: 'Brazil',
    native: 'Brasil',
    languages: ['pt'],
    emoji: '🇧🇷',
  },
  BS: {
    name: 'Bahamas',
    native: 'Bahamas',
    languages: ['en'],
    emoji: '🇧🇸',
  },
  BT: {
    name: 'Bhutan',
    native: 'ʼbrug-yul',
    languages: ['dz'],
    emoji: '🇧🇹',
  },
  BV: {
    name: 'Bouvet Island',
    native: 'Bouvetøya',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇧🇻',
  },
  BW: {
    name: 'Botswana',
    native: 'Botswana',
    languages: ['en', 'tn'],
    emoji: '🇧🇼',
  },
  BY: {
    name: 'Belarus',
    native: 'Белару́сь',
    languages: ['be', 'ru'],
    emoji: '🇧🇾',
  },
  BZ: {
    name: 'Belize',
    native: 'Belize',
    languages: ['en', 'es'],
    emoji: '🇧🇿',
  },
  CA: {
    name: 'Canada',
    native: 'Canada',
    languages: ['en', 'fr'],
    emoji: '🇨🇦',
  },
  CC: {
    name: 'Cocos (Keeling) Islands',
    native: 'Cocos (Keeling) Islands',
    languages: ['en'],
    emoji: '🇨🇨',
  },
  CD: {
    name: 'Democratic Republic of the Congo',
    native: 'République démocratique du Congo',
    languages: ['fr', 'ln', 'kg', 'sw', 'lu'],
    emoji: '🇨🇩',
  },
  CF: {
    name: 'Central African Republic',
    native: 'Ködörösêse tî Bêafrîka',
    languages: ['fr', 'sg'],
    emoji: '🇨🇫',
  },
  CG: {
    name: 'Republic of the Congo',
    native: 'République du Congo',
    languages: ['fr', 'ln'],
    emoji: '🇨🇬',
  },
  CH: {
    name: 'Switzerland',
    native: 'Schweiz',
    languages: ['de', 'fr', 'it'],
    emoji: '🇨🇭',
  },
  CI: {
    name: 'Ivory Coast',
    native: "Côte d'Ivoire",
    languages: ['fr'],
    emoji: '🇨🇮',
  },
  CK: {
    name: 'Cook Islands',
    native: 'Cook Islands',
    languages: ['en'],
    emoji: '🇨🇰',
  },
  CL: {
    name: 'Chile',
    native: 'Chile',
    languages: ['es'],
    emoji: '🇨🇱',
  },
  CM: {
    name: 'Cameroon',
    native: 'Cameroon',
    languages: ['en', 'fr'],
    emoji: '🇨🇲',
  },
  CN: {
    name: 'China',
    native: '中国',
    languages: ['zh'],
    emoji: '🇨🇳',
  },
  CO: {
    name: 'Colombia',
    native: 'Colombia',
    languages: ['es'],
    emoji: '🇨🇴',
  },
  CR: {
    name: 'Costa Rica',
    native: 'Costa Rica',
    languages: ['es'],
    emoji: '🇨🇷',
  },
  CU: {
    name: 'Cuba',
    native: 'Cuba',
    languages: ['es'],
    emoji: '🇨🇺',
  },
  CV: {
    name: 'Cape Verde',
    native: 'Cabo Verde',
    languages: ['pt'],
    emoji: '🇨🇻',
  },
  CW: {
    name: 'Curacao',
    native: 'Curaçao',
    languages: ['nl', 'pa', 'en'],
    emoji: '🇨🇼',
  },
  CX: {
    name: 'Christmas Island',
    native: 'Christmas Island',
    languages: ['en'],
    emoji: '🇨🇽',
  },
  CY: {
    name: 'Cyprus',
    native: 'Κύπρος',
    languages: ['el', 'tr', 'hy'],
    emoji: '🇨🇾',
  },
  CZ: {
    name: 'Czech Republic',
    native: 'Česká republika',
    languages: ['cs'],
    emoji: '🇨🇿',
  },
  DE: {
    name: 'Germany',
    native: 'Deutschland',
    languages: ['de'],
    emoji: '🇩🇪',
  },
  DJ: {
    name: 'Djibouti',
    native: 'Djibouti',
    languages: ['fr', 'ar'],
    emoji: '🇩🇯',
  },
  DK: {
    name: 'Denmark',
    native: 'Danmark',
    languages: ['da'],
    emoji: '🇩🇰',
  },
  DM: {
    name: 'Dominica',
    native: 'Dominica',
    languages: ['en'],
    emoji: '🇩🇲',
  },
  DO: {
    name: 'Dominican Republic',
    native: 'República Dominicana',
    languages: ['es'],
    emoji: '🇩🇴',
  },
  DZ: {
    name: 'Algeria',
    native: 'الجزائر',
    languages: ['ar'],
    emoji: '🇩🇿',
  },
  EC: {
    name: 'Ecuador',
    native: 'Ecuador',
    languages: ['es'],
    emoji: '🇪🇨',
  },
  EE: {
    name: 'Estonia',
    native: 'Eesti',
    languages: ['et'],
    emoji: '🇪🇪',
  },
  EG: {
    name: 'Egypt',
    native: 'مصر‎',
    languages: ['ar'],
    emoji: '🇪🇬',
  },
  EH: {
    name: 'Western Sahara',
    native: 'الصحراء الغربية',
    languages: ['es'],
    emoji: '🇪🇭',
  },
  ER: {
    name: 'Eritrea',
    native: 'ኤርትራ',
    languages: ['ti', 'ar', 'en'],
    emoji: '🇪🇷',
  },
  ES: {
    name: 'Spain',
    native: 'España',
    languages: ['es', 'eu', 'ca', 'gl', 'oc'],
    emoji: '🇪🇸',
  },
  ET: {
    name: 'Ethiopia',
    native: 'ኢትዮጵያ',
    languages: ['am'],
    emoji: '🇪🇹',
  },
  FI: {
    name: 'Finland',
    native: 'Suomi',
    languages: ['fi', 'sv'],
    emoji: '🇫🇮',
  },
  FJ: {
    name: 'Fiji',
    native: 'Fiji',
    languages: ['en', 'fj', 'hi', 'ur'],
    emoji: '🇫🇯',
  },
  FK: {
    name: 'Falkland Islands',
    native: 'Falkland Islands',
    languages: ['en'],
    emoji: '🇫🇰',
  },
  FM: {
    name: 'Micronesia',
    native: 'Micronesia',
    languages: ['en'],
    emoji: '🇫🇲',
  },
  FO: {
    name: 'Faroe Islands',
    native: 'Føroyar',
    languages: ['fo'],
    emoji: '🇫🇴',
  },
  FR: {
    name: 'France',
    native: 'France',
    languages: ['fr'],
    emoji: '🇫🇷',
  },
  GA: {
    name: 'Gabon',
    native: 'Gabon',
    languages: ['fr'],
    emoji: '🇬🇦',
  },
  GB: {
    name: 'United Kingdom',
    native: 'United Kingdom',
    languages: ['en'],
    emoji: '🇬🇧',
  },
  GD: {
    name: 'Grenada',
    native: 'Grenada',
    languages: ['en'],
    emoji: '🇬🇩',
  },
  GE: {
    name: 'Georgia',
    native: 'საქართველო',
    languages: ['ka'],
    emoji: '🇬🇪',
  },
  GF: {
    name: 'French Guiana',
    native: 'Guyane française',
    languages: ['fr'],
    emoji: '🇬🇫',
  },
  GG: {
    name: 'Guernsey',
    native: 'Guernsey',
    languages: ['en', 'fr'],
    emoji: '🇬🇬',
  },
  GH: {
    name: 'Ghana',
    native: 'Ghana',
    languages: ['en'],
    emoji: '🇬🇭',
  },
  GI: {
    name: 'Gibraltar',
    native: 'Gibraltar',
    languages: ['en'],
    emoji: '🇬🇮',
  },
  GL: {
    name: 'Greenland',
    native: 'Kalaallit Nunaat',
    languages: ['kl'],
    emoji: '🇬🇱',
  },
  GM: {
    name: 'Gambia',
    native: 'Gambia',
    languages: ['en'],
    emoji: '🇬🇲',
  },
  GN: {
    name: 'Guinea',
    native: 'Guinée',
    languages: ['fr', 'ff'],
    emoji: '🇬🇳',
  },
  GP: {
    name: 'Guadeloupe',
    native: 'Guadeloupe',
    languages: ['fr'],
    emoji: '🇬🇵',
  },
  GQ: {
    name: 'Equatorial Guinea',
    native: 'Guinea Ecuatorial',
    languages: ['es', 'fr'],
    emoji: '🇬🇶',
  },
  GR: {
    name: 'Greece',
    native: 'Ελλάδα',
    languages: ['el'],
    emoji: '🇬🇷',
  },
  GS: {
    name: 'South Georgia and the South Sandwich Islands',
    native: 'South Georgia',
    languages: ['en'],
    emoji: '🇬🇸',
  },
  GT: {
    name: 'Guatemala',
    native: 'Guatemala',
    languages: ['es'],
    emoji: '🇬🇹',
  },
  GU: {
    name: 'Guam',
    native: 'Guam',
    languages: ['en', 'ch', 'es'],
    emoji: '🇬🇺',
  },
  GW: {
    name: 'Guinea-Bissau',
    native: 'Guiné-Bissau',
    languages: ['pt'],
    emoji: '🇬🇼',
  },
  GY: {
    name: 'Guyana',
    native: 'Guyana',
    languages: ['en'],
    emoji: '🇬🇾',
  },
  HK: {
    name: 'Hong Kong',
    native: '香港',
    languages: ['zh', 'en'],
    emoji: '🇭🇰',
  },
  HM: {
    name: 'Heard Island and McDonald Islands',
    native: 'Heard Island and McDonald Islands',
    languages: ['en'],
    emoji: '🇭🇲',
  },
  HN: {
    name: 'Honduras',
    native: 'Honduras',
    languages: ['es'],
    emoji: '🇭🇳',
  },
  HR: {
    name: 'Croatia',
    native: 'Hrvatska',
    languages: ['hr'],
    emoji: '🇭🇷',
  },
  HT: {
    name: 'Haiti',
    native: 'Haïti',
    languages: ['fr', 'ht'],
    emoji: '🇭🇹',
  },
  HU: {
    name: 'Hungary',
    native: 'Magyarország',
    languages: ['hu'],
    emoji: '🇭🇺',
  },
  ID: {
    name: 'Indonesia',
    native: 'Indonesia',
    languages: ['id'],
    emoji: '🇮🇩',
  },
  IE: {
    name: 'Ireland',
    native: 'Éire',
    languages: ['ga', 'en'],
    emoji: '🇮🇪',
  },
  IL: {
    name: 'Israel',
    native: 'יִשְׂרָאֵל',
    languages: ['he', 'ar'],
    emoji: '🇮🇱',
  },
  IM: {
    name: 'Isle of Man',
    native: 'Isle of Man',
    languages: ['en', 'gv'],
    emoji: '🇮🇲',
  },
  IN: {
    name: 'India',
    native: 'भारत',
    languages: ['hi', 'en'],
    emoji: '🇮🇳',
  },
  IO: {
    name: 'British Indian Ocean Territory',
    native: 'British Indian Ocean Territory',
    languages: ['en'],
    emoji: '🇮🇴',
  },
  IQ: {
    name: 'Iraq',
    native: 'العراق',
    languages: ['ar', 'ku'],
    emoji: '🇮🇶',
  },
  IR: {
    name: 'Iran',
    native: 'ایران',
    languages: ['fa'],
    emoji: '🇮🇷',
  },
  IS: {
    name: 'Iceland',
    native: 'Ísland',
    languages: ['is'],
    emoji: '🇮🇸',
  },
  IT: {
    name: 'Italy',
    native: 'Italia',
    languages: ['it'],
    emoji: '🇮🇹',
  },
  JE: {
    name: 'Jersey',
    native: 'Jersey',
    languages: ['en', 'fr'],
    emoji: '🇯🇪',
  },
  JM: {
    name: 'Jamaica',
    native: 'Jamaica',
    languages: ['en'],
    emoji: '🇯🇲',
  },
  JO: {
    name: 'Jordan',
    native: 'الأردن',
    languages: ['ar'],
    emoji: '🇯🇴',
  },
  JP: {
    name: 'Japan',
    native: '日本',
    languages: ['ja'],
    emoji: '🇯🇵',
  },
  KE: {
    name: 'Kenya',
    native: 'Kenya',
    languages: ['en', 'sw'],
    emoji: '🇰🇪',
  },
  KG: {
    name: 'Kyrgyzstan',
    native: 'Кыргызстан',
    languages: ['ky', 'ru'],
    emoji: '🇰🇬',
  },
  KH: {
    name: 'Cambodia',
    native: 'Kâmpŭchéa',
    languages: ['km'],
    emoji: '🇰🇭',
  },
  KI: {
    name: 'Kiribati',
    native: 'Kiribati',
    languages: ['en'],
    emoji: '🇰🇮',
  },
  KM: {
    name: 'Comoros',
    native: 'Komori',
    languages: ['ar', 'fr'],
    emoji: '🇰🇲',
  },
  KN: {
    name: 'Saint Kitts and Nevis',
    native: 'Saint Kitts and Nevis',
    languages: ['en'],
    emoji: '🇰🇳',
  },
  KP: {
    name: 'North Korea',
    native: '북한',
    languages: ['ko'],
    emoji: '🇰🇵',
  },
  KR: {
    name: 'South Korea',
    native: '대한민국',
    languages: ['ko'],
    emoji: '🇰🇷',
  },
  KW: {
    name: 'Kuwait',
    native: 'الكويت',
    languages: ['ar'],
    emoji: '🇰🇼',
  },
  KY: {
    name: 'Cayman Islands',
    native: 'Cayman Islands',
    languages: ['en'],
    emoji: '🇰🇾',
  },
  KZ: {
    name: 'Kazakhstan',
    native: 'Қазақстан',
    languages: ['kk', 'ru'],
    emoji: '🇰🇿',
  },
  LA: {
    name: 'Laos',
    native: 'ສປປລາວ',
    languages: ['lo'],
    emoji: '🇱🇦',
  },
  LB: {
    name: 'Lebanon',
    native: 'لبنان',
    languages: ['ar', 'fr'],
    emoji: '🇱🇧',
  },
  LC: {
    name: 'Saint Lucia',
    native: 'Saint Lucia',
    languages: ['en'],
    emoji: '🇱🇨',
  },
  LI: {
    name: 'Liechtenstein',
    native: 'Liechtenstein',
    languages: ['de'],
    emoji: '🇱🇮',
  },
  LK: {
    name: 'Sri Lanka',
    native: 'śrī laṃkāva',
    languages: ['si', 'ta'],
    emoji: '🇱🇰',
  },
  LR: {
    name: 'Liberia',
    native: 'Liberia',
    languages: ['en'],
    emoji: '🇱🇷',
  },
  LS: {
    name: 'Lesotho',
    native: 'Lesotho',
    languages: ['en', 'st'],
    emoji: '🇱🇸',
  },
  LT: {
    name: 'Lithuania',
    native: 'Lietuva',
    languages: ['lt'],
    emoji: '🇱🇹',
  },
  LU: {
    name: 'Luxembourg',
    native: 'Luxembourg',
    languages: ['fr', 'de', 'lb'],
    emoji: '🇱🇺',
  },
  LV: {
    name: 'Latvia',
    native: 'Latvija',
    languages: ['lv'],
    emoji: '🇱🇻',
  },
  LY: {
    name: 'Libya',
    native: '‏ليبيا',
    languages: ['ar'],
    emoji: '🇱🇾',
  },
  MA: {
    name: 'Morocco',
    native: 'المغرب',
    languages: ['ar'],
    emoji: '🇲🇦',
  },
  MC: {
    name: 'Monaco',
    native: 'Monaco',
    languages: ['fr'],
    emoji: '🇲🇨',
  },
  MD: {
    name: 'Moldova',
    native: 'Moldova',
    languages: ['ro'],
    emoji: '🇲🇩',
  },
  ME: {
    name: 'Montenegro',
    native: 'Црна Гора',
    languages: ['sr', 'bs', 'sq', 'hr'],
    emoji: '🇲🇪',
  },
  MF: {
    name: 'Saint Martin',
    native: 'Saint-Martin',
    languages: ['en', 'fr', 'nl'],
    emoji: '🇲🇫',
  },
  MG: {
    name: 'Madagascar',
    native: 'Madagasikara',
    languages: ['fr', 'mg'],
    emoji: '🇲🇬',
  },
  MH: {
    name: 'Marshall Islands',
    native: 'M̧ajeļ',
    languages: ['en', 'mh'],
    emoji: '🇲🇭',
  },
  MK: {
    name: 'North Macedonia',
    native: 'Северна Македонија',
    languages: ['mk'],
    emoji: '🇲🇰',
  },
  ML: {
    name: 'Mali',
    native: 'Mali',
    languages: ['fr'],
    emoji: '🇲🇱',
  },
  MM: {
    name: 'Myanmar (Burma)',
    native: 'မြန်မာ',
    languages: ['my'],
    emoji: '🇲🇲',
  },
  MN: {
    name: 'Mongolia',
    native: 'Монгол улс',
    languages: ['mn'],
    emoji: '🇲🇳',
  },
  MO: {
    name: 'Macao',
    native: '澳門',
    languages: ['zh', 'pt'],
    emoji: '🇲🇴',
  },
  MP: {
    name: 'Northern Mariana Islands',
    native: 'Northern Mariana Islands',
    languages: ['en', 'ch'],
    emoji: '🇲🇵',
  },
  MQ: {
    name: 'Martinique',
    native: 'Martinique',
    languages: ['fr'],
    emoji: '🇲🇶',
  },
  MR: {
    name: 'Mauritania',
    native: 'موريتانيا',
    languages: ['ar'],
    emoji: '🇲🇷',
  },
  MS: {
    name: 'Montserrat',
    native: 'Montserrat',
    languages: ['en'],
    emoji: '🇲🇸',
  },
  MT: {
    name: 'Malta',
    native: 'Malta',
    languages: ['mt', 'en'],
    emoji: '🇲🇹',
  },
  MU: {
    name: 'Mauritius',
    native: 'Maurice',
    languages: ['en'],
    emoji: '🇲🇺',
  },
  MV: {
    name: 'Maldives',
    native: 'Maldives',
    languages: ['dv'],
    emoji: '🇲🇻',
  },
  MW: {
    name: 'Malawi',
    native: 'Malawi',
    languages: ['en', 'ny'],
    emoji: '🇲🇼',
  },
  MX: {
    name: 'Mexico',
    native: 'México',
    languages: ['es'],
    emoji: '🇲🇽',
  },
  MY: {
    name: 'Malaysia',
    native: 'Malaysia',
    languages: ['ms'],
    emoji: '🇲🇾',
  },
  MZ: {
    name: 'Mozambique',
    native: 'Moçambique',
    languages: ['pt'],
    emoji: '🇲🇿',
  },
  NA: {
    name: 'Namibia',
    native: 'Namibia',
    languages: ['en', 'af'],
    emoji: '🇳🇦',
  },
  NC: {
    name: 'New Caledonia',
    native: 'Nouvelle-Calédonie',
    languages: ['fr'],
    emoji: '🇳🇨',
  },
  NE: {
    name: 'Niger',
    native: 'Niger',
    languages: ['fr'],
    emoji: '🇳🇪',
  },
  NF: {
    name: 'Norfolk Island',
    native: 'Norfolk Island',
    languages: ['en'],
    emoji: '🇳🇫',
  },
  NG: {
    name: 'Nigeria',
    native: 'Nigeria',
    languages: ['en'],
    emoji: '🇳🇬',
  },
  NI: {
    name: 'Nicaragua',
    native: 'Nicaragua',
    languages: ['es'],
    emoji: '🇳🇮',
  },
  NL: {
    name: 'Netherlands',
    native: 'Nederland',
    languages: ['nl'],
    emoji: '🇳🇱',
  },
  NO: {
    name: 'Norway',
    native: 'Norge',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇳🇴',
  },
  NP: {
    name: 'Nepal',
    native: 'नेपाल',
    languages: ['ne'],
    emoji: '🇳🇵',
  },
  NR: {
    name: 'Nauru',
    native: 'Nauru',
    languages: ['en', 'na'],
    emoji: '🇳🇷',
  },
  NU: {
    name: 'Niue',
    native: 'Niuē',
    languages: ['en'],
    emoji: '🇳🇺',
  },
  NZ: {
    name: 'New Zealand',
    native: 'New Zealand',
    languages: ['en', 'mi'],
    emoji: '🇳🇿',
  },
  OM: {
    name: 'Oman',
    native: 'عمان',
    languages: ['ar'],
    emoji: '🇴🇲',
  },
  PA: {
    name: 'Panama',
    native: 'Panamá',
    languages: ['es'],
    emoji: '🇵🇦',
  },
  PE: {
    name: 'Peru',
    native: 'Perú',
    languages: ['es'],
    emoji: '🇵🇪',
  },
  PF: {
    name: 'French Polynesia',
    native: 'Polynésie française',
    languages: ['fr'],
    emoji: '🇵🇫',
  },
  PG: {
    name: 'Papua New Guinea',
    native: 'Papua Niugini',
    languages: ['en'],
    emoji: '🇵🇬',
  },
  PH: {
    name: 'Philippines',
    native: 'Pilipinas',
    languages: ['en'],
    emoji: '🇵🇭',
  },
  PK: {
    name: 'Pakistan',
    native: 'Pakistan',
    languages: ['en', 'ur'],
    emoji: '🇵🇰',
  },
  PL: {
    name: 'Poland',
    native: 'Polska',
    languages: ['pl'],
    emoji: '🇵🇱',
  },
  PM: {
    name: 'Saint Pierre and Miquelon',
    native: 'Saint-Pierre-et-Miquelon',
    languages: ['fr'],
    emoji: '🇵🇲',
  },
  PN: {
    name: 'Pitcairn Islands',
    native: 'Pitcairn Islands',
    languages: ['en'],
    emoji: '🇵🇳',
  },
  PR: {
    name: 'Puerto Rico',
    native: 'Puerto Rico',
    languages: ['es', 'en'],
    emoji: '🇵🇷',
  },
  PS: {
    name: 'Palestine',
    native: 'فلسطين',
    languages: ['ar'],
    emoji: '🇵🇸',
  },
  PT: {
    name: 'Portugal',
    native: 'Portugal',
    languages: ['pt'],
    emoji: '🇵🇹',
  },
  PW: {
    name: 'Palau',
    native: 'Palau',
    languages: ['en'],
    emoji: '🇵🇼',
  },
  PY: {
    name: 'Paraguay',
    native: 'Paraguay',
    languages: ['es', 'gn'],
    emoji: '🇵🇾',
  },
  QA: {
    name: 'Qatar',
    native: 'قطر',
    languages: ['ar'],
    emoji: '🇶🇦',
  },
  RE: {
    name: 'Reunion',
    native: 'La Réunion',
    languages: ['fr'],
    emoji: '🇷🇪',
  },
  RO: {
    name: 'Romania',
    native: 'România',
    languages: ['ro'],
    emoji: '🇷🇴',
  },
  RS: {
    name: 'Serbia',
    native: 'Србија',
    languages: ['sr'],
    emoji: '🇷🇸',
  },
  RU: {
    name: 'Russia',
    native: 'Россия',
    languages: ['ru'],
    emoji: '🇷🇺',
  },
  RW: {
    name: 'Rwanda',
    native: 'Rwanda',
    languages: ['rw', 'en', 'fr'],
    emoji: '🇷🇼',
  },
  SA: {
    name: 'Saudi Arabia',
    native: 'العربية السعودية',
    languages: ['ar'],
    emoji: '🇸🇦',
  },
  SB: {
    name: 'Solomon Islands',
    native: 'Solomon Islands',
    languages: ['en'],
    emoji: '🇸🇧',
  },
  SC: {
    name: 'Seychelles',
    native: 'Seychelles',
    languages: ['fr', 'en'],
    emoji: '🇸🇨',
  },
  SD: {
    name: 'Sudan',
    native: 'السودان',
    languages: ['ar', 'en'],
    emoji: '🇸🇩',
  },
  SE: {
    name: 'Sweden',
    native: 'Sverige',
    languages: ['sv'],
    emoji: '🇸🇪',
  },
  SG: {
    name: 'Singapore',
    native: 'Singapore',
    languages: ['en', 'ms', 'ta', 'zh'],
    emoji: '🇸🇬',
  },
  SH: {
    name: 'Saint Helena',
    native: 'Saint Helena',
    languages: ['en'],
    emoji: '🇸🇭',
  },
  SI: {
    name: 'Slovenia',
    native: 'Slovenija',
    languages: ['sl'],
    emoji: '🇸🇮',
  },
  SJ: {
    name: 'Svalbard and Jan Mayen',
    native: 'Svalbard og Jan Mayen',
    languages: ['no'],
    emoji: '🇸🇯',
  },
  SK: {
    name: 'Slovakia',
    native: 'Slovensko',
    languages: ['sk'],
    emoji: '🇸🇰',
  },
  SL: {
    name: 'Sierra Leone',
    native: 'Sierra Leone',
    languages: ['en'],
    emoji: '🇸🇱',
  },
  SM: {
    name: 'San Marino',
    native: 'San Marino',
    languages: ['it'],
    emoji: '🇸🇲',
  },
  SN: {
    name: 'Senegal',
    native: 'Sénégal',
    languages: ['fr'],
    emoji: '🇸🇳',
  },
  SO: {
    name: 'Somalia',
    native: 'Soomaaliya',
    languages: ['so', 'ar'],
    emoji: '🇸🇴',
  },
  SR: {
    name: 'Suriname',
    native: 'Suriname',
    languages: ['nl'],
    emoji: '🇸🇷',
  },
  SS: {
    name: 'South Sudan',
    native: 'South Sudan',
    languages: ['en'],
    emoji: '🇸🇸',
  },
  ST: {
    name: 'Sao Tome and Principe',
    native: 'São Tomé e Príncipe',
    languages: ['pt'],
    emoji: '🇸🇹',
  },
  SV: {
    name: 'El Salvador',
    native: 'El Salvador',
    languages: ['es'],
    emoji: '🇸🇻',
  },
  SX: {
    name: 'Sint Maarten',
    native: 'Sint Maarten',
    languages: ['nl', 'en'],
    emoji: '🇸🇽',
  },
  SY: {
    name: 'Syria',
    native: 'سوريا',
    languages: ['ar'],
    emoji: '🇸🇾',
  },
  SZ: {
    name: 'Eswatini',
    native: 'Eswatini',
    languages: ['en', 'ss'],
    emoji: '🇸🇿',
  },
  TC: {
    name: 'Turks and Caicos Islands',
    native: 'Turks and Caicos Islands',
    languages: ['en'],
    emoji: '🇹🇨',
  },
  TD: {
    name: 'Chad',
    native: 'Tchad',
    languages: ['fr', 'ar'],
    emoji: '🇹🇩',
  },
  TF: {
    name: 'French Southern Territories',
    native: 'Territoire des Terres australes et antarctiques fr',
    languages: ['fr'],
    emoji: '🇹🇫',
  },
  TG: {
    name: 'Togo',
    native: 'Togo',
    languages: ['fr'],
    emoji: '🇹🇬',
  },
  TH: {
    name: 'Thailand',
    native: 'ประเทศไทย',
    languages: ['th'],
    emoji: '🇹🇭',
  },
  TJ: {
    name: 'Tajikistan',
    native: 'Тоҷикистон',
    languages: ['tg', 'ru'],
    emoji: '🇹🇯',
  },
  TK: {
    name: 'Tokelau',
    native: 'Tokelau',
    languages: ['en'],
    emoji: '🇹🇰',
  },
  TL: {
    name: 'East Timor',
    native: 'Timor-Leste',
    languages: ['pt'],
    emoji: '🇹🇱',
  },
  TM: {
    name: 'Turkmenistan',
    native: 'Türkmenistan',
    languages: ['tk', 'ru'],
    emoji: '🇹🇲',
  },
  TN: {
    name: 'Tunisia',
    native: 'تونس',
    languages: ['ar'],
    emoji: '🇹🇳',
  },
  TO: {
    name: 'Tonga',
    native: 'Tonga',
    languages: ['en', 'to'],
    emoji: '🇹🇴',
  },
  TR: {
    name: 'Turkey',
    native: 'Türkiye',
    languages: ['tr'],
    emoji: '🇹🇷',
  },
  TT: {
    name: 'Trinidad and Tobago',
    native: 'Trinidad and Tobago',
    languages: ['en'],
    emoji: '🇹🇹',
  },
  TV: {
    name: 'Tuvalu',
    native: 'Tuvalu',
    languages: ['en'],
    emoji: '🇹🇻',
  },
  TW: {
    name: 'Taiwan',
    native: '臺灣',
    languages: ['zh'],
    emoji: '🇹🇼',
  },
  TZ: {
    name: 'Tanzania',
    native: 'Tanzania',
    languages: ['sw', 'en'],
    emoji: '🇹🇿',
  },
  UA: {
    name: 'Ukraine',
    native: 'Україна',
    languages: ['uk'],
    emoji: '🇺🇦',
  },
  UG: {
    name: 'Uganda',
    native: 'Uganda',
    languages: ['en', 'sw'],
    emoji: '🇺🇬',
  },
  UM: {
    name: 'U.S. Minor Outlying Islands',
    native: 'United States Minor Outlying Islands',
    languages: ['en'],
    emoji: '🇺🇲',
  },
  US: {
    name: 'United States',
    native: 'United States',
    languages: ['en'],
    emoji: '🇺🇸',
  },
  UY: {
    name: 'Uruguay',
    native: 'Uruguay',
    languages: ['es'],
    emoji: '🇺🇾',
  },
  UZ: {
    name: 'Uzbekistan',
    native: "O'zbekiston",
    languages: ['uz', 'ru'],
    emoji: '🇺🇿',
  },
  VA: {
    name: 'Vatican City',
    native: 'Vaticano',
    languages: ['it', 'la'],
    emoji: '🇻🇦',
  },
  VC: {
    name: 'Saint Vincent and the Grenadines',
    native: 'Saint Vincent and the Grenadines',
    languages: ['en'],
    emoji: '🇻🇨',
  },
  VE: {
    name: 'Venezuela',
    native: 'Venezuela',
    languages: ['es'],
    emoji: '🇻🇪',
  },
  VG: {
    name: 'British Virgin Islands',
    native: 'British Virgin Islands',
    languages: ['en'],
    emoji: '🇻🇬',
  },
  VI: {
    name: 'U.S. Virgin Islands',
    native: 'United States Virgin Islands',
    languages: ['en'],
    emoji: '🇻🇮',
  },
  VN: {
    name: 'Vietnam',
    native: 'Việt Nam',
    languages: ['vi'],
    emoji: '🇻🇳',
  },
  VU: {
    name: 'Vanuatu',
    native: 'Vanuatu',
    languages: ['bi', 'en', 'fr'],
    emoji: '🇻🇺',
  },
  WF: {
    name: 'Wallis and Futuna',
    native: 'Wallis et Futuna',
    languages: ['fr'],
    emoji: '🇼🇫',
  },
  WS: {
    name: 'Samoa',
    native: 'Samoa',
    languages: ['sm', 'en'],
    emoji: '🇼🇸',
  },
  /**
   * The code XK is being used by the European Commission the IMF, and SWIFT, the CLDR,
   * and other organizations as a temporary country code for Kosovo.
   */
  XK: {
    name: 'Kosovo',
    native: 'Republika e Kosovës',
    languages: ['sq', 'sr'],
    emoji: '🇽🇰',
    userAssigned: true,
  },
  YE: {
    name: 'Yemen',
    native: 'اليَمَن',
    languages: ['ar'],
    emoji: '🇾🇪',
  },
  YT: {
    name: 'Mayotte',
    native: 'Mayotte',
    languages: ['fr'],
    emoji: '🇾🇹',
  },
  ZA: {
    name: 'South Africa',
    native: 'South Africa',
    languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
    emoji: '🇿🇦',
  },
  ZM: {
    name: 'Zambia',
    native: 'Zambia',
    languages: ['en'],
    emoji: '🇿🇲',
  },
  ZW: {
    name: 'Zimbabwe',
    native: 'Zimbabwe',
    languages: ['en', 'sn', 'nd'],
    emoji: '🇿🇼',
  },
}
