export const languages = {
  aa: {
    name: 'Afar',
    native: 'Afar',
    emoji: '🇩🇯',
    countries: ['DJ', 'ER', 'ET'],
  },
  ab: {
    name: 'Abkhazian',
    native: 'Аҧсуа',
    emoji: '🇬🇪',
    countries: ['GE'],
  },
  af: {
    name: 'Afrikaans',
    native: 'Afrikaans',
    emoji: '🇿🇦',
    countries: ['ZA', 'NA'],
  },
  ak: {
    name: 'Akan',
    native: 'Akana',
    emoji: '🇬🇭',
    countries: ['GH', 'CI'],
  },
  am: {
    name: 'Amharic',
    native: 'አማርኛ',
    emoji: '🇪🇹',
    countries: ['ET'],
  },
  an: {
    name: 'Aragonese',
    native: 'Aragonés',
    emoji: '🇪🇸',
    countries: ['ES'],
  },
  ar: {
    name: 'Arabic',
    native: 'العربية',
    emoji: '🇸🇦',
    countries: [
      'EG',
      'DZ',
      'SD',
      'IQ',
      'MA',
      'SA',
      'YE',
      'SY',
      'TN',
      'JO',
      'AE',
      'LY',
      'LB',
      'OM',
      'KW',
      'MR',
      'QA',
      'BH',
      'PS',
      'DJ',
      'KM',
      'ER',
      'SO',
      'TD',
    ],
    rtl: 1,
  },
  as: {
    name: 'Assamese',
    native: 'অসমীয়া',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  av: {
    name: 'Avar',
    native: 'Авар',
    emoji: '🇷🇺',
    countries: ['RU'],
  },
  ay: {
    name: 'Aymara',
    native: 'Aymar',
    emoji: '🇧🇴',
    countries: ['BO', 'PE'],
  },
  az: {
    name: 'Azerbaijani',
    native: 'Azərbaycanca / آذربايجان',
    emoji: '🇦🇿',
    countries: ['AZ', 'IR'],
  },
  ba: {
    name: 'Bashkir',
    native: 'Башҡорт',
    emoji: '🇷🇺',
    countries: ['RU'],
  },
  be: {
    name: 'Belarusian',
    native: 'Беларуская',
    emoji: '🇧🇾',
    countries: ['BY'],
  },
  bg: {
    name: 'Bulgarian',
    native: 'Български',
    emoji: '🇧🇬',
    countries: ['BG'],
  },
  bh: {
    name: 'Bihari',
    native: 'भोजपुरी',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  bi: {
    name: 'Bislama',
    native: 'Bislama',
    emoji: '🇻🇺',
    countries: ['VU'],
  },
  bm: {
    name: 'Bambara',
    native: 'Bamanankan',
    emoji: '🇲🇱',
    countries: ['ML'],
  },
  bn: {
    name: 'Bengali',
    native: 'বাংলা',
    emoji: '🇧🇩',
    countries: ['BD', 'IN'],
  },
  bo: {
    name: 'Tibetan',
    native: 'བོད་ཡིག / Bod skad',
    emoji: '🇨🇳',
    countries: ['CN'],
  },
  br: {
    name: 'Breton',
    native: 'Brezhoneg',
    emoji: '🇫🇷',
    countries: ['FR'],
  },
  bs: {
    name: 'Bosnian',
    native: 'Bosanski',
    emoji: '🇧🇦',
    countries: ['BA', 'ME'],
  },
  ca: {
    name: 'Catalan',
    native: 'Català',
    emoji: '🇦🇩',
    countries: ['AD', 'ES', 'IT', 'FR'],
  },
  ce: {
    name: 'Chechen',
    native: 'Нохчийн',
    emoji: '🇷🇺',
    countries: ['RU'],
  },
  ch: {
    name: 'Chamorro',
    native: 'Chamoru',
    emoji: '🇬🇺',
    countries: ['GU', 'MP'],
  },
  co: {
    name: 'Corsican',
    native: 'Corsu',
    emoji: '🇫🇷',
    countries: ['FR', 'IT'],
  },
  cr: {
    name: 'Cree',
    native: 'Nehiyaw',
    emoji: '🇨🇦',
    countries: ['CA'],
  },
  cs: {
    name: 'Czech',
    native: 'Čeština',
    emoji: '🇨🇿',
    countries: ['CZ'],
  },
  cu: {
    name: 'Old Church Slavonic / Old Bulgarian',
    native: 'словѣньскъ / slověnĭskŭ',
    emoji: '🇧🇬',
    countries: [], // Historically in Bulgaria
  },
  cv: {
    name: 'Chuvash',
    native: 'Чăваш',
    emoji: '🇷🇺',
    countries: ['RU'],
  },
  cy: {
    name: 'Welsh',
    native: 'Cymraeg',
    emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    countries: ['GB'],
  },
  da: {
    name: 'Danish',
    native: 'Dansk',
    emoji: '🇩🇰',
    countries: ['DK', 'FO', 'GL'],
  },
  de: {
    name: 'German',
    native: 'Deutsch',
    emoji: '🇩🇪',
    countries: ['DE', 'AT', 'CH', 'LI', 'LU', 'BE'],
  },
  dv: {
    name: 'Divehi',
    native: 'ދިވެހިބަސް',
    emoji: '🇲🇻',
    countries: ['MV'],
    rtl: 1,
  },
  dz: {
    name: 'Dzongkha',
    native: 'ཇོང་ཁ',
    emoji: '🇧🇹',
    countries: ['BT'],
  },
  ee: {
    name: 'Ewe',
    native: 'Ɛʋɛ',
    emoji: '🇬🇭',
    countries: ['GH', 'TG'],
  },
  el: {
    name: 'Greek',
    native: 'Ελληνικά',
    emoji: '🇬🇷',
    countries: ['GR', 'CY'],
  },
  en: {
    name: 'English',
    native: 'English',
    emoji: '🇬🇧',
    countries: [
      'US',
      'GB',
      'CA',
      'AU',
      'NZ',
      'IE',
      'ZA',
      'NG',
      'IN',
      'PK',
      'PH',
    ],
  },
  eo: {
    name: 'Esperanto',
    native: 'Esperanto',
    emoji: '🏳️',
    countries: [],
  },
  es: {
    name: 'Spanish',
    native: 'Español',
    emoji: '🇪🇸',
    countries: [
      'MX',
      'CO',
      'AR',
      'ES',
      'PE',
      'VE',
      'CL',
      'EC',
      'GT',
      'CU',
      'BO',
      'HN',
      'PY',
      'SV',
      'NI',
      'CR',
      'PA',
      'UY',
      'GQ',
    ],
  },
  et: {
    name: 'Estonian',
    native: 'Eesti',
    emoji: '🇪🇪',
    countries: ['EE'],
  },
  eu: {
    name: 'Basque',
    native: 'Euskara',
    emoji: '🇪🇸',
    countries: ['ES', 'FR'],
  },
  fa: {
    name: 'Persian',
    native: 'فارسی',
    emoji: '🇮🇷',
    countries: ['IR', 'AF', 'TJ'],
    rtl: 1,
  },
  ff: {
    name: 'Peul',
    native: 'Fulfulde',
    emoji: '🇳🇬',
    countries: ['NG', 'SN', 'GN', 'CM', 'NE', 'BF', 'ML'],
  },
  fi: {
    name: 'Finnish',
    native: 'Suomi',
    emoji: '🇫🇮',
    countries: ['FI'],
  },
  fj: {
    name: 'Fijian',
    native: 'Na Vosa Vakaviti',
    emoji: '🇫🇯',
    countries: ['FJ'],
  },
  fo: {
    name: 'Faroese',
    native: 'Føroyskt',
    emoji: '🇫🇴',
    countries: ['FO'],
  },
  fr: {
    name: 'French',
    native: 'Français',
    emoji: '🇫🇷',
    countries: [
      'FR',
      'CD',
      'CA',
      'CM',
      'CI',
      'BE',
      'SN',
      'CH',
      'GN',
      'ML',
      'BF',
      'TG',
      'CG',
      'LU',
      'MC',
    ],
  },
  fy: {
    name: 'West Frisian',
    native: 'Frysk',
    emoji: '🇳🇱',
    countries: ['NL'],
  },
  ga: {
    name: 'Irish',
    native: 'Gaeilge',
    emoji: '🇮🇪',
    countries: ['IE'],
  },
  gd: {
    name: 'Scottish Gaelic',
    native: 'Gàidhlig',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    countries: ['GB'],
  },
  gl: {
    name: 'Galician',
    native: 'Galego',
    emoji: '🇪🇸',
    countries: ['ES'],
  },
  gn: {
    name: 'Guarani',
    native: "Avañe'ẽ",
    emoji: '🇵🇾',
    countries: ['PY', 'BO', 'AR'],
  },
  gu: {
    name: 'Gujarati',
    native: 'ગુજરાતી',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  gv: {
    name: 'Manx',
    native: 'Gaelg',
    emoji: '🇮🇲',
    countries: ['IM'],
  },
  ha: {
    name: 'Hausa',
    native: 'هَوُسَ',
    emoji: '🇳🇬',
    countries: ['NG', 'NE', 'GH', 'CM', 'SD'],
    rtl: 1,
  },
  he: {
    name: 'Hebrew',
    native: 'עברית',
    emoji: '🇮🇱',
    countries: ['IL'],
    rtl: 1,
  },
  hi: {
    name: 'Hindi',
    native: 'हिन्दी',
    emoji: '🇮🇳',
    countries: ['IN', 'FJ', 'NP'],
  },
  ho: {
    name: 'Hiri Motu',
    native: 'Hiri Motu',
    emoji: '🇵🇬',
    countries: ['PG'],
  },
  hr: {
    name: 'Croatian',
    native: 'Hrvatski',
    emoji: '🇭🇷',
    countries: ['HR', 'BA', 'ME'],
  },
  ht: {
    name: 'Haitian',
    native: 'Krèyol ayisyen',
    emoji: '🇭🇹',
    countries: ['HT'],
  },
  hu: {
    name: 'Hungarian',
    native: 'Magyar',
    emoji: '🇭🇺',
    countries: ['HU'],
  },
  hy: {
    name: 'Armenian',
    native: 'Հայերեն',
    emoji: '🇦🇲',
    countries: ['AM'],
  },
  hz: {
    name: 'Herero',
    native: 'Otsiherero',
    emoji: '🇳🇦',
    countries: ['NA'],
  },
  ia: {
    name: 'Interlingua',
    native: 'Interlingua',
    emoji: '🏳️',
    countries: [],
  },
  id: {
    name: 'Indonesian',
    native: 'Bahasa Indonesia',
    emoji: '🇮🇩',
    countries: ['ID'],
  },
  ie: {
    name: 'Interlingue',
    native: 'Interlingue',
    emoji: '🏳️',
    countries: [],
  },
  ig: {
    name: 'Igbo',
    native: 'Igbo',
    emoji: '🇳🇬',
    countries: ['NG'],
  },
  ii: {
    name: 'Sichuan Yi',
    native: 'ꆇꉙ / 四川彝语',
    emoji: '🇨🇳',
    countries: ['CN'],
  },
  ik: {
    name: 'Inupiak',
    native: 'Iñupiak',
    emoji: '🇺🇸',
    countries: ['US'],
  },
  io: {
    name: 'Ido',
    native: 'Ido',
    emoji: '🏳️',
    countries: [],
  },
  is: {
    name: 'Icelandic',
    native: 'Íslenska',
    emoji: '🇮🇸',
    countries: ['IS'],
  },
  it: {
    name: 'Italian',
    native: 'Italiano',
    emoji: '🇮🇹',
    countries: ['IT', 'CH', 'SM', 'VA'],
  },
  iu: {
    name: 'Inuktitut',
    native: 'ᐃᓄᒃᑎᑐᑦ',
    emoji: '🇨🇦',
    countries: ['CA'],
  },
  ja: {
    name: 'Japanese',
    native: '日本語',
    emoji: '🇯🇵',
    countries: ['JP'],
  },
  jv: {
    name: 'Javanese',
    native: 'Basa Jawa',
    emoji: '🇮🇩',
    countries: ['ID'],
  },
  ka: {
    name: 'Georgian',
    native: 'ქართული',
    emoji: '🇬🇪',
    countries: ['GE'],
  },
  kg: {
    name: 'Kongo',
    native: 'KiKongo',
    emoji: '🇨🇩',
    countries: ['CD', 'CG', 'AO'],
  },
  ki: {
    name: 'Kikuyu',
    native: 'Gĩkũyũ',
    emoji: '🇰🇪',
    countries: ['KE'],
  },
  kj: {
    name: 'Kuanyama',
    native: 'Kuanyama',
    emoji: '🇦🇴',
    countries: ['AO', 'NA'],
  },
  kk: {
    name: 'Kazakh',
    native: 'Қазақша',
    emoji: '🇰🇿',
    countries: ['KZ'],
  },
  kl: {
    name: 'Greenlandic',
    native: 'Kalaallisut',
    emoji: '🇬🇱',
    countries: ['GL'],
  },
  km: {
    name: 'Cambodian',
    native: 'ភាសាខ្មែរ',
    emoji: '🇰🇭',
    countries: ['KH'],
  },
  kn: {
    name: 'Kannada',
    native: 'ಕನ್ನಡ',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  ko: {
    name: 'Korean',
    native: '한국어',
    emoji: '🇰🇷',
    countries: ['KR', 'KP'],
  },
  kr: {
    name: 'Kanuri',
    native: 'Kanuri',
    emoji: '🇳🇬',
    countries: ['NG'],
  },
  ks: {
    name: 'Kashmiri',
    native: 'कश्मीरी / كشميري',
    emoji: '🇮🇳',
    countries: ['IN', 'PK'],
    rtl: 1,
  },
  ku: {
    name: 'Kurdish',
    native: 'Kurdî / كوردی',
    emoji: '🇮🇶',
    countries: ['IQ', 'TR', 'IR', 'SY'],
    rtl: 1,
  },
  kv: {
    name: 'Komi',
    native: 'Коми',
    emoji: '🇷🇺',
    countries: ['RU'],
  },
  kw: {
    name: 'Cornish',
    native: 'Kernewek',
    emoji: '🇬🇧',
    countries: ['GB'],
  },
  ky: {
    name: 'Kyrgyz',
    native: 'Кыргызча',
    emoji: '🇰🇬',
    countries: ['KG'],
  },
  la: {
    name: 'Latin',
    native: 'Latina',
    emoji: '🇻🇦',
    countries: ['VA'],
  },
  lb: {
    name: 'Luxembourgish',
    native: 'Lëtzebuergesch',
    emoji: '🇱🇺',
    countries: ['LU'],
  },
  lg: {
    name: 'Ganda',
    native: 'Luganda',
    emoji: '🇺🇬',
    countries: ['UG'],
  },
  li: {
    name: 'Limburgian',
    native: 'Limburgs',
    emoji: '🇳🇱',
    countries: ['NL', 'BE', 'DE'],
  },
  ln: {
    name: 'Lingala',
    native: 'Lingála',
    emoji: '🇨🇩',
    countries: ['CD', 'CG'],
  },
  lo: {
    name: 'Laotian',
    native: 'ລາວ / Pha xa lao',
    emoji: '🇱🇦',
    countries: ['LA'],
  },
  lt: {
    name: 'Lithuanian',
    native: 'Lietuvių',
    emoji: '🇱🇹',
    countries: ['LT'],
  },
  lu: {
    name: 'Luba-Katanga',
    native: 'Tshiluba',
    emoji: '🇨🇩',
    countries: ['CD'],
  },
  lv: {
    name: 'Latvian',
    native: 'Latviešu',
    emoji: '🇱🇻',
    countries: ['LV'],
  },
  mg: {
    name: 'Malagasy',
    native: 'Malagasy',
    emoji: '🇲🇬',
    countries: ['MG'],
  },
  mh: {
    name: 'Marshallese',
    native: 'Kajin Majel / Ebon',
    emoji: '🇲🇭',
    countries: ['MH'],
  },
  mi: {
    name: 'Maori',
    native: 'Māori',
    emoji: '🇳🇿',
    countries: ['NZ'],
  },
  mk: {
    name: 'Macedonian',
    native: 'Македонски',
    emoji: '🇲🇰',
    countries: ['MK'],
  },
  ml: {
    name: 'Malayalam',
    native: 'മലയാളം',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  mn: {
    name: 'Mongolian',
    native: 'Монгол',
    emoji: '🇲🇳',
    countries: ['MN'],
  },
  mo: {
    name: 'Moldovan',
    native: 'Moldovenească',
    emoji: '🇲🇩',
    countries: ['MD'],
  },
  mr: {
    name: 'Marathi',
    native: 'मराठी',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  ms: {
    name: 'Malay',
    native: 'Bahasa Melayu',
    emoji: '🇲🇾',
    countries: ['MY', 'BN', 'SG', 'ID'],
  },
  mt: {
    name: 'Maltese',
    native: 'bil-Malti',
    emoji: '🇲🇹',
    countries: ['MT'],
  },
  my: {
    name: 'Burmese',
    native: 'မြန်မာစာ',
    emoji: '🇲🇲',
    countries: ['MM'],
  },
  na: {
    name: 'Nauruan',
    native: 'Dorerin Naoero',
    emoji: '🇳🇷',
    countries: ['NR'],
  },
  nb: {
    name: 'Norwegian Bokmål',
    native: 'Norsk bokmål',
    emoji: '🇳🇴',
    countries: ['NO'],
  },
  nd: {
    name: 'North Ndebele',
    native: 'Sindebele',
    emoji: '🇿🇼',
    countries: ['ZW'],
  },
  ne: {
    name: 'Nepali',
    native: 'नेपाली',
    emoji: '🇳🇵',
    countries: ['NP', 'IN'],
  },
  ng: {
    name: 'Ndonga',
    native: 'Oshiwambo',
    emoji: '🇳🇦',
    countries: ['NA'],
  },
  nl: {
    name: 'Dutch',
    native: 'Nederlands',
    emoji: '🇳🇱',
    countries: ['NL', 'BE', 'SR', 'AW', 'CW', 'SX'],
  },
  nn: {
    name: 'Norwegian Nynorsk',
    native: 'Norsk nynorsk',
    emoji: '🇳🇴',
    countries: ['NO'],
  },
  no: {
    name: 'Norwegian',
    native: 'Norsk',
    emoji: '🇳🇴',
    countries: ['NO', 'SJ'],
  },
  nr: {
    name: 'South Ndebele',
    native: 'isiNdebele',
    emoji: '🇿🇦',
    countries: ['ZA'],
  },
  nv: {
    name: 'Navajo',
    native: 'Diné bizaad',
    emoji: '🇺🇸',
    countries: ['US'],
  },
  ny: {
    name: 'Chichewa',
    native: 'Chi-Chewa',
    emoji: '🇲🇼',
    countries: ['MW', 'ZM', 'MZ'],
  },
  oc: {
    name: 'Occitan',
    native: 'Occitan',
    emoji: '🇫🇷',
    countries: ['FR', 'ES', 'IT'],
  },
  oj: {
    name: 'Ojibwa',
    native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin',
    emoji: '🇨🇦',
    countries: ['CA', 'US'],
  },
  om: {
    name: 'Oromo',
    native: 'Oromoo',
    emoji: '🇪🇹',
    countries: ['ET', 'KE'],
  },
  or: {
    name: 'Oriya',
    native: 'ଓଡ଼ିଆ',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  os: {
    name: 'Ossetian / Ossetic',
    native: 'Иронау',
    emoji: '🇬🇪',
    countries: ['GE', 'RU'],
  },
  pa: {
    name: 'Panjabi / Punjabi',
    native: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
    emoji: '🇮🇳',
    countries: ['IN', 'PK'],
  },
  pi: {
    name: 'Pali',
    native: 'Pāli / पाऴि',
    emoji: '🇮🇳',
    countries: [], // Ancient language of India
  },
  pl: {
    name: 'Polish',
    native: 'Polski',
    emoji: '🇵🇱',
    countries: ['PL'],
  },
  ps: {
    name: 'Pashto',
    native: 'پښتو',
    emoji: '🇦🇫',
    countries: ['AF', 'PK'],
    rtl: 1,
  },
  pt: {
    name: 'Portuguese',
    native: 'Português',
    emoji: '🇵🇹',
    countries: ['BR', 'PT', 'AO', 'MZ', 'CV', 'GW', 'ST', 'TL', 'GQ'],
  },
  qu: {
    name: 'Quechua',
    native: 'Runa Simi',
    emoji: '🇵🇪',
    countries: ['PE', 'BO', 'EC'],
  },
  rm: {
    name: 'Raeto Romance',
    native: 'Rumantsch',
    emoji: '🇨🇭',
    countries: ['CH'],
  },
  rn: {
    name: 'Kirundi',
    native: 'Kirundi',
    emoji: '🇧🇮',
    countries: ['BI'],
  },
  ro: {
    name: 'Romanian',
    native: 'Română',
    emoji: '🇷🇴',
    countries: ['RO', 'MD'],
  },
  ru: {
    name: 'Russian',
    native: 'Русский',
    emoji: '🇷🇺',
    countries: ['RU', 'UA', 'BY', 'KZ', 'KG', 'TJ', 'UZ', 'TM', 'AM'],
  },
  rw: {
    name: 'Rwandi',
    native: 'Kinyarwandi',
    emoji: '🇷🇼',
    countries: ['RW'],
  },
  sa: {
    name: 'Sanskrit',
    native: 'संस्कृतम्',
    emoji: '🇮🇳',
    countries: [], // Ancient language of India
  },
  sc: {
    name: 'Sardinian',
    native: 'Sardu',
    emoji: '🇮🇹',
    countries: ['IT'],
  },
  sd: {
    name: 'Sindhi',
    native: 'सिनधि',
    emoji: '🇵🇰',
    countries: ['PK', 'IN'],
  },
  se: {
    name: 'Northern Sami',
    native: 'Sámegiella',
    emoji: '🇳🇴',
    countries: ['NO', 'SE', 'FI'],
  },
  sg: {
    name: 'Sango',
    native: 'Sängö',
    emoji: '🇨🇫',
    countries: ['CF'],
  },
  sh: {
    name: 'Serbo-Croatian',
    native: 'Srpskohrvatski / Српскохрватски',
    emoji: '🏳️',
    countries: ['RS', 'HR', 'BA', 'ME'],
  },
  si: {
    name: 'Sinhalese',
    native: 'සිංහල',
    emoji: '🇱🇰',
    countries: ['LK'],
  },
  sk: {
    name: 'Slovak',
    native: 'Slovenčina',
    emoji: '🇸🇰',
    countries: ['SK'],
  },
  sl: {
    name: 'Slovenian',
    native: 'Slovenščina',
    emoji: '🇸🇮',
    countries: ['SI'],
  },
  sm: {
    name: 'Samoan',
    native: 'Gagana Samoa',
    emoji: '🇼🇸',
    countries: ['WS', 'AS'],
  },
  sn: {
    name: 'Shona',
    native: 'chiShona',
    emoji: '🇿🇼',
    countries: ['ZW'],
  },
  so: {
    name: 'Somalia',
    native: 'Soomaaliga',
    emoji: '🇸🇴',
    countries: ['SO', 'DJ', 'ET', 'KE'],
  },
  sq: {
    name: 'Albanian',
    native: 'Shqip',
    emoji: '🇦🇱',
    countries: ['AL', 'XK', 'MK', 'ME'],
  },
  sr: {
    name: 'Serbian',
    native: 'Српски',
    emoji: '🇷🇸',
    countries: ['RS', 'BA', 'ME', 'XK'],
  },
  ss: {
    name: 'Swati',
    native: 'SiSwati',
    emoji: '🇸🇿',
    countries: ['SZ', 'ZA'],
  },
  st: {
    name: 'Southern Sotho',
    native: 'Sesotho',
    emoji: '🇱🇸',
    countries: ['LS', 'ZA'],
  },
  su: {
    name: 'Sundanese',
    native: 'Basa Sunda',
    emoji: '🇮🇩',
    countries: ['ID'],
  },
  sv: {
    name: 'Swedish',
    native: 'Svenska',
    emoji: '🇸🇪',
    countries: ['SE', 'FI', 'AX'],
  },
  sw: {
    name: 'Swahili',
    native: 'Kiswahili',
    emoji: '🇹🇿',
    countries: ['TZ', 'KE', 'UG', 'CD', 'RW'],
  },
  ta: {
    name: 'Tamil',
    native: 'தமிழ்',
    emoji: '🇮🇳',
    countries: ['IN', 'LK', 'SG', 'MY'],
  },
  te: {
    name: 'Telugu',
    native: 'తెలుగు',
    emoji: '🇮🇳',
    countries: ['IN'],
  },
  tg: {
    name: 'Tajik',
    native: 'Тоҷикӣ',
    emoji: '🇹🇯',
    countries: ['TJ'],
  },
  th: {
    name: 'Thai',
    native: 'ไทย / Phasa Thai',
    emoji: '🇹🇭',
    countries: ['TH'],
  },
  ti: {
    name: 'Tigrinya',
    native: 'ትግርኛ',
    emoji: '🇪🇷',
    countries: ['ER', 'ET'],
  },
  tk: {
    name: 'Turkmen',
    native: 'Туркмен / تركمن',
    emoji: '🇹🇲',
    countries: ['TM'],
  },
  tl: {
    name: 'Tagalog / Filipino',
    native: 'Tagalog',
    emoji: '🇵🇭',
    countries: ['PH'],
  },
  tn: {
    name: 'Tswana',
    native: 'Setswana',
    emoji: '🇧🇼',
    countries: ['BW', 'ZA'],
  },
  to: {
    name: 'Tonga',
    native: 'Lea Faka-Tonga',
    emoji: '🇹🇴',
    countries: ['TO'],
  },
  tr: {
    name: 'Turkish',
    native: 'Türkçe',
    emoji: '🇹🇷',
    countries: ['TR', 'CY'],
  },
  ts: {
    name: 'Tsonga',
    native: 'Xitsonga',
    emoji: '🇿🇦',
    countries: ['ZA', 'MZ', 'ZW'],
  },
  tt: {
    name: 'Tatar',
    native: 'Tatarça',
    emoji: '🇷🇺',
    countries: ['RU'],
  },
  tw: {
    name: 'Twi',
    native: 'Twi',
    emoji: '🇬🇭',
    countries: ['GH'],
  },
  ty: {
    name: 'Tahitian',
    native: 'Reo Mā`ohi',
    emoji: '🇵🇫',
    countries: ['PF'],
  },
  ug: {
    name: 'Uyghur',
    native: 'Uyƣurqə / ئۇيغۇرچە',
    emoji: '🇨🇳',
    countries: ['CN'],
  },
  uk: {
    name: 'Ukrainian',
    native: 'Українська',
    emoji: '🇺🇦',
    countries: ['UA'],
  },
  ur: {
    name: 'Urdu',
    native: 'اردو',
    emoji: '🇵🇰',
    countries: ['PK', 'IN'],
    rtl: 1,
  },
  uz: {
    name: 'Uzbek',
    native: "O'zbekcha",
    emoji: '🇺🇿',
    countries: ['UZ'],
  },
  ve: {
    name: 'Venda',
    native: 'Tshivenḓa',
    emoji: '🇿🇦',
    countries: ['ZA'],
  },
  vi: {
    name: 'Vietnamese',
    native: 'Tiếng Việt',
    emoji: '🇻🇳',
    countries: ['VN'],
  },
  vo: {
    name: 'Volapük',
    native: 'Volapük',
    emoji: '🏳️',
    countries: [],
  },
  wa: {
    name: 'Walloon',
    native: 'Walon',
    emoji: '🇧🇪',
    countries: ['BE'],
  },
  wo: {
    name: 'Wolof',
    native: 'Wollof',
    emoji: '🇸🇳',
    countries: ['SN', 'GM', 'MR'],
  },
  xh: {
    name: 'Xhosa',
    native: 'isiXhosa',
    emoji: '🇿🇦',
    countries: ['ZA'],
  },
  yi: {
    name: 'Yiddish',
    native: 'ייִדיש',
    emoji: '🏳️',
    countries: ['IL', 'US'],
    rtl: 1,
  },
  yo: {
    name: 'Yoruba',
    native: 'Yorùbá',
    emoji: '🇳🇬',
    countries: ['NG', 'BJ', 'TG'],
  },
  za: {
    name: 'Zhuang',
    native: 'Cuengh / Tôô / 壮语',
    emoji: '🇨🇳',
    countries: ['CN'],
  },
  cn: {
    name: 'Cantonese',
    native: '廣州話',
    emoji: '🇨🇳',
    countries: ['CN', 'TW', 'SG', 'HK', 'MO'],
  },
  zh: {
    name: 'Chinese',
    native: '中文',
    emoji: '🇨🇳',
    countries: ['CN', 'TW', 'SG', 'HK', 'MO'],
  },
  zu: {
    name: 'Zulu',
    native: 'isiZulu',
    emoji: '🇿🇦',
    countries: ['ZA'],
  },
}
