import { Movie, Person, Cast, Crew } from '../interfaces'

export const genres = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
]

export const departments = [
  'Acting',
  'Directing',
  'Writing',
  'Crew',
  'Art',
  'Sound',
  'Lighting',
  'Editing',
  'Production',
  'Visual Effects',
  'Camera',
  'Costume & Make-Up',
]

export const movie = {
  adult: false,
  backdrop_path: '/ByDf0zjLSumz1MP1cDEo2JWVtU.jpg',
  belongs_to_collection: {
    id: 2344,
    name: 'Matrix - Saga',
    poster_path: '/6qkUJ7KjSHsz6XXOTTZu4THV2PP.jpg',
    backdrop_path: '/bRm2DEgUiYciDw3myHuYFInD7la.jpg',
  },
  budget: 63000000,
  genres: [
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 878,
      name: 'Science-Fiction',
    },
  ],
  homepage: 'http://www.warnerbros.com/matrix',
  id: 603,
  imdb_id: 'tt0133093',
  plex_url: null,
  original_language: 'en',
  original_title: 'The Matrix',
  overview:
    "Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l'un des pirates les plus recherchés du cyber-espace. À cheval entre deux mondes, Neo est assailli par d'étranges songes et des messages cryptés provenant d'un certain Morpheus. Celui-ci l'exhorte à aller au-delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées : qu'est-ce que la Matrice ? Nul ne le sait, et aucun homme n'est encore parvenu à en percer les défenses. Mais Morpheus est persuadé que Neo est l’Élu, le libérateur mythique de l'humanité annoncé selon la prophétie. Ensemble, ils se lancent dans une lutte sans retour contre la Matrice et ses terribles agents...",
  popularity: 50.433,
  poster_path: '/pEoqbqtLc4CcwDUDqxmEDSWpWTZ.jpg',
  release: null,
  production_companies: [
    {
      id: 79,
      logo_path: '/tpFpsqbleCzEE2p5EgvUq6ozfCA.png',
      name: 'Village Roadshow Pictures',
      origin_country: 'US',
    },
    {
      id: 372,
      logo_path: null,
      name: 'Groucho II Film Partnership',
      origin_country: '',
    },
    {
      id: 1885,
      logo_path: '/xlvoOZr4s1PygosrwZyolIFe5xs.png',
      name: 'Silver Pictures',
      origin_country: 'US',
    },
    {
      id: 174,
      logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
      name: 'Warner Bros. Pictures',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'AU',
      name: 'Australia',
    },
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '1999-03-30',
  revenue: 463517383,
  runtime: 135,
  spoken_languages: [
    {
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: "Croire à l'incroyable",
  title: 'Matrix',
  video: false,
  vote_average: 8.1,
  vote_count: 17477,
  credits: {
    cast: [
      {
        cast_id: 34,
        character: 'Thomas A. Anderson / Neo',
        credit_id: '52fe425bc3a36847f80181c1',
        gender: 2,
        id: 6384,
        name: 'Keanu Reeves',
        order: 0,
        profile_path: '/d9HyjGMCt4wgJIOxAGlaYWhKsiN.jpg',
      },
      {
        cast_id: 21,
        character: 'Morpheus',
        credit_id: '52fe425bc3a36847f801818d',
        gender: 2,
        id: 2975,
        name: 'Laurence Fishburne',
        order: 1,
        profile_path: '/8suOhUmPbfKqDQ17jQ1Gy0mI3P4.jpg',
      },
      {
        cast_id: 22,
        character: 'Trinity',
        credit_id: '52fe425bc3a36847f8018191',
        gender: 1,
        id: 530,
        name: 'Carrie-Anne Moss',
        order: 2,
        profile_path: '/9zya72vRZYBQILfetACsnmCBgdj.jpg',
      },
      {
        cast_id: 23,
        character: 'Agent Smith',
        credit_id: '52fe425bc3a36847f8018195',
        gender: 2,
        id: 1331,
        name: 'Hugo Weaving',
        order: 3,
        profile_path: '/7eDl1FXoHUlic95WHf96RICtL9N.jpg',
      },
      {
        cast_id: 25,
        character: 'Cypher',
        credit_id: '52fe425bc3a36847f801819d',
        gender: 2,
        id: 532,
        name: 'Joe Pantoliano',
        order: 4,
        profile_path: '/aDOm4xPRtIwBpLd8O2oCz0aVC3s.jpg',
      },
      {
        cast_id: 24,
        character: 'Oracle',
        credit_id: '52fe425bc3a36847f8018199',
        gender: 1,
        id: 9364,
        name: 'Gloria Foster',
        order: 5,
        profile_path: '/AriGXtC9fjBOia9Zr8CZjn4o3rx.jpg',
      },
      {
        cast_id: 26,
        character: 'Tank',
        credit_id: '52fe425bc3a36847f80181a1',
        gender: 2,
        id: 9372,
        name: 'Marcus Chong',
        order: 6,
        profile_path: '/q9HQttibTj2MoXVtLjq2kKqmPrE.jpg',
      },
      {
        cast_id: 31,
        character: 'Agent Brown',
        credit_id: '52fe425bc3a36847f80181b5',
        gender: 2,
        id: 9380,
        name: 'Paul Goddard',
        order: 7,
        profile_path: '/z6XP6Xhkh5ZE88gBOz2FnVQaKuf.jpg',
      },
      {
        cast_id: 38,
        character: 'Agent Jones',
        credit_id: '52fe425bc3a36847f80181cb',
        gender: 2,
        id: 39545,
        name: 'Robert Taylor',
        order: 8,
        profile_path: '/uzhk2Gp8UL5IiaYRBJRddinjj8e.jpg',
      },
      {
        cast_id: 27,
        character: 'Apoc',
        credit_id: '52fe425bc3a36847f80181a5',
        gender: 2,
        id: 7244,
        name: 'Julian Arahanga',
        order: 9,
        profile_path: '/g2YkF3PWSJU1vTKuURBH0DOMblm.jpg',
      },
      {
        cast_id: 29,
        character: 'Switch',
        credit_id: '52fe425bc3a36847f80181ad',
        gender: 1,
        id: 9376,
        name: 'Belinda McClory',
        order: 10,
        profile_path: '/wfTCwkIDJjH5k5DtuvcjP52PrLc.jpg',
      },
      {
        cast_id: 30,
        character: 'Dozer',
        credit_id: '52fe425bc3a36847f80181b1',
        gender: 2,
        id: 9378,
        name: 'Anthony Ray Parker',
        order: 11,
        profile_path: '/k03O1ClFvGRSedUnK0sAjTkrogX.jpg',
      },
      {
        cast_id: 28,
        character: 'Mouse',
        credit_id: '52fe425bc3a36847f80181a9',
        gender: 2,
        id: 9374,
        name: 'Matt Doran',
        order: 12,
        profile_path: '/4HtMShAbsZ2AyFtq5z3bOVrvw2s.jpg',
      },
      {
        cast_id: 39,
        character: 'DuJour',
        credit_id: '52fe425bc3a36847f80181cf',
        gender: 1,
        id: 181214,
        name: 'Ada Nicodemou',
        order: 13,
        profile_path: '/mJ0mxYYXEAcy52UHbQbGdBiip2c.jpg',
      },
      {
        cast_id: 32,
        character: 'Rhineheart',
        credit_id: '52fe425bc3a36847f80181b9',
        gender: 2,
        id: 9383,
        name: 'David Aston',
        order: 14,
        profile_path: '/98TG57IaWdMGBG41NHsUIWtecPX.jpg',
      },
      {
        cast_id: 33,
        character: 'Choi',
        credit_id: '52fe425bc3a36847f80181bd',
        gender: 2,
        id: 9384,
        name: 'Marc Aden Gray',
        order: 15,
        profile_path: null,
      },
      {
        cast_id: 40,
        character: 'Priestess',
        credit_id: '52fe425bc3a36847f80181d3',
        gender: 0,
        id: 1090466,
        name: 'Deni Gordon',
        order: 16,
        profile_path: null,
      },
      {
        cast_id: 41,
        character: 'Spoon Boy',
        credit_id: '52fe425bc3a36847f80181d7',
        gender: 2,
        id: 218366,
        name: 'Rowan Witt',
        order: 17,
        profile_path: null,
      },
      {
        cast_id: 43,
        character: 'Potential',
        credit_id: '52fe425bc3a36847f80181df',
        gender: 0,
        id: 1209244,
        name: 'Eleanor Witt',
        order: 18,
        profile_path: null,
      },
      {
        cast_id: 44,
        character: 'Potential',
        credit_id: '52fe425bc3a36847f80181e3',
        gender: 1,
        id: 1209245,
        name: 'Tamara Brown',
        order: 19,
        profile_path: '/Y6PpJtEFlCPbb2Vn0ubjTPjCtr.jpg',
      },
      {
        cast_id: 45,
        character: 'Potential',
        credit_id: '52fe425bc3a36847f80181e7',
        gender: 1,
        id: 1209246,
        name: 'Janaya Pender',
        order: 20,
        profile_path: '/vp5zai4UhXnjT56Wo61WJAtAZdm.jpg',
      },
      {
        cast_id: 46,
        character: 'Potential',
        credit_id: '52fe425bc3a36847f80181eb',
        gender: 0,
        id: 1209247,
        name: 'Adryn White',
        order: 21,
        profile_path: null,
      },
      {
        cast_id: 47,
        character: 'Potential',
        credit_id: '52fe425bc3a36847f80181ef',
        gender: 0,
        id: 1209248,
        name: 'Natalie Tjen',
        order: 22,
        profile_path: null,
      },
      {
        cast_id: 42,
        character: 'Lieutenant',
        credit_id: '52fe425bc3a36847f80181db',
        gender: 2,
        id: 57799,
        name: 'Bill Young',
        order: 23,
        profile_path: null,
      },
      {
        cast_id: 48,
        character: 'FedEx Man',
        credit_id: '52fe425bc3a36847f80181f3',
        gender: 0,
        id: 1209249,
        name: "David O'Connor",
        order: 24,
        profile_path: null,
      },
      {
        cast_id: 49,
        character: 'Businessman',
        credit_id: '52fe425bc3a36847f80181f7',
        gender: 0,
        id: 1209250,
        name: 'Jeremy Ball',
        order: 25,
        profile_path: null,
      },
      {
        cast_id: 50,
        character: 'Woman in Red',
        credit_id: '52fe425bc3a36847f80181fb',
        gender: 0,
        id: 1209251,
        name: 'Fiona Johnson',
        order: 26,
        profile_path: null,
      },
      {
        cast_id: 51,
        character: 'Old Man',
        credit_id: '52fe425bc3a36847f80181ff',
        gender: 2,
        id: 110411,
        name: 'Harry Lawrence',
        order: 27,
        profile_path: '/73cUjTwh7q8TGqbCX9reMQsdmDm.jpg',
      },
      {
        cast_id: 52,
        character: 'Blind Man',
        credit_id: '52fe425bc3a36847f8018203',
        gender: 0,
        id: 212562,
        name: 'Steve Dodd',
        order: 28,
        profile_path: null,
      },
      {
        cast_id: 53,
        character: 'Security Guard',
        credit_id: '52fe425bc3a36847f8018207',
        gender: 0,
        id: 1209252,
        name: 'Luke Quinton',
        order: 29,
        profile_path: null,
      },
      {
        cast_id: 54,
        character: 'Guard',
        credit_id: '52fe425cc3a36847f801820b',
        gender: 0,
        id: 75715,
        name: 'Lawrence Woodward',
        order: 30,
        profile_path: null,
      },
      {
        cast_id: 55,
        character: 'Cop Who Captures Neo',
        credit_id: '52fe425cc3a36847f801820f',
        gender: 0,
        id: 1209253,
        name: 'Michael Butcher',
        order: 31,
        profile_path: null,
      },
      {
        cast_id: 56,
        character: 'Big Cop',
        credit_id: '52fe425cc3a36847f8018213',
        gender: 0,
        id: 1209254,
        name: 'Bernard Ledger',
        order: 32,
        profile_path: null,
      },
      {
        cast_id: 57,
        character: 'Cop',
        credit_id: '52fe425cc3a36847f8018217',
        gender: 2,
        id: 26753,
        name: 'Robert Simper',
        order: 33,
        profile_path: null,
      },
      {
        cast_id: 58,
        character: 'Cop',
        credit_id: '52fe425cc3a36847f801821b',
        gender: 1,
        id: 1209255,
        name: 'Chris Pattinson',
        order: 34,
        profile_path: null,
      },
      {
        cast_id: 59,
        character: 'Parking Cop',
        credit_id: '52fe425cc3a36847f801821f',
        gender: 2,
        id: 1209256,
        name: 'Nigel Harbach',
        order: 35,
        profile_path: null,
      },
      {
        cast_id: 129,
        character: 'Shaylea',
        credit_id: '5eb47e440cb3350020c97a04',
        gender: 1,
        id: 1209257,
        name: 'Rana Morrison',
        order: 36,
        profile_path: '/8ALyJkb2lith9kEVHY5IpECYSQR.jpg',
      },
    ],
    crew: [
      {
        credit_id: '5831cc6d92514162d2027340',
        department: 'Production',
        gender: 2,
        id: 123,
        job: 'Executive Producer',
        name: 'Barrie M. Osborne',
        profile_path: '/xWtXYk6M5NFroddcQDviLlxOnkU.jpg',
      },
      {
        credit_id: '52fe425bc3a36847f801812f',
        department: 'Production',
        gender: 2,
        id: 1091,
        job: 'Producer',
        name: 'Joel Silver',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f8018147',
        department: 'Production',
        gender: 1,
        id: 1262,
        job: 'Casting',
        name: 'Mali Finn',
        profile_path: null,
      },
      {
        credit_id: '5831cd3392514162d202741f',
        department: 'Production',
        gender: 2,
        id: 1296,
        job: 'Executive Producer',
        name: 'Bruce Berman',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f8018141',
        department: 'Editing',
        gender: 2,
        id: 4671,
        job: 'Editor',
        name: 'Zach Staenberg',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f8018135',
        department: 'Sound',
        gender: 2,
        id: 4949,
        job: 'Original Music Composer',
        name: 'Don Davis',
        profile_path: '/FUcQUEOFH18BqYAeIs8VFud1E4.jpg',
      },
      {
        credit_id: '52fe425bc3a36847f801816b',
        department: 'Costume & Make-Up',
        gender: 1,
        id: 6209,
        job: 'Costume Design',
        name: 'Kym Barrett',
        profile_path: '/wphQYPxu1Jr82JrEQWtTApX7Kys.jpg',
      },
      {
        credit_id: '5831d14cc3a3685ba8027740',
        department: 'Art',
        gender: 1,
        id: 6411,
        job: 'Set Designer',
        name: 'Deborah Riley',
        profile_path: '/cjhADpqdrnwB1PdDUKaBnWrIj2Q.jpg',
      },
      {
        credit_id: '52fe425bc3a36847f801813b',
        department: 'Camera',
        gender: 2,
        id: 9341,
        job: 'Director of Photography',
        name: 'Bill Pope',
        profile_path: '/f53VXtMCZqOr5Df9V4hRTuT0yfp.jpg',
      },
      {
        credit_id: '5831cd20c3a3685b9a0275df',
        department: 'Production',
        gender: 2,
        id: 10950,
        job: 'Executive Producer',
        name: 'Erwin Stoff',
        profile_path: null,
      },
      {
        credit_id: '5831cc77c3a3685ba102b4a5',
        department: 'Production',
        gender: 2,
        id: 8299,
        job: 'Executive Producer',
        name: 'Andrew Mason',
        profile_path: null,
      },
      {
        credit_id: '571756cfc3a3687c2c000a63',
        department: 'Directing',
        gender: 1,
        id: 9339,
        job: 'Director',
        name: 'Lilly Wachowski',
        profile_path: '/9sxE10LUA7TGlS1pHw2RM6mckHp.jpg',
      },
      {
        credit_id: '5831ccfe92514162d8026200',
        department: 'Production',
        gender: 1,
        id: 9339,
        job: 'Executive Producer',
        name: 'Lilly Wachowski',
        profile_path: '/9sxE10LUA7TGlS1pHw2RM6mckHp.jpg',
      },
      {
        credit_id: '5831cbe1c3a3685bad024e78',
        department: 'Writing',
        gender: 1,
        id: 9339,
        job: 'Writer',
        name: 'Lilly Wachowski',
        profile_path: '/9sxE10LUA7TGlS1pHw2RM6mckHp.jpg',
      },
      {
        credit_id: '571756c4c3a3687bc70008e9',
        department: 'Directing',
        gender: 1,
        id: 9340,
        job: 'Director',
        name: 'Lana Wachowski',
        profile_path: '/ppGicszb7PxGDAI2F6qBTXrn1t0.jpg',
      },
      {
        credit_id: '5831ccf2c3a3685bb0025cbd',
        department: 'Production',
        gender: 1,
        id: 9340,
        job: 'Executive Producer',
        name: 'Lana Wachowski',
        profile_path: '/ppGicszb7PxGDAI2F6qBTXrn1t0.jpg',
      },
      {
        credit_id: '5831cbea92514162d80260e5',
        department: 'Writing',
        gender: 1,
        id: 9340,
        job: 'Writer',
        name: 'Lana Wachowski',
        profile_path: '/ppGicszb7PxGDAI2F6qBTXrn1t0.jpg',
      },
      {
        credit_id: '52fe425bc3a36847f801814d',
        department: 'Production',
        gender: 0,
        id: 9342,
        job: 'Casting',
        name: 'Shauna Wolifson',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f8018153',
        department: 'Art',
        gender: 2,
        id: 9343,
        job: 'Production Design',
        name: 'Owen Paterson',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f8018159',
        department: 'Art',
        gender: 2,
        id: 9344,
        job: 'Art Direction',
        name: 'Hugh Bateup',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f801815f',
        department: 'Art',
        gender: 1,
        id: 9345,
        job: 'Art Direction',
        name: 'Michelle McGahey',
        profile_path: null,
      },
      {
        credit_id: '52fe425bc3a36847f8018165',
        department: 'Art',
        gender: 1,
        id: 9346,
        job: 'Set Decoration',
        name: 'Lisa Brennan',
        profile_path: null,
      },
      {
        credit_id: '5831cf1492514162c3026dfe',
        department: 'Sound',
        gender: 2,
        id: 9349,
        job: 'Sound Designer',
        name: 'Dane A. Davis',
        profile_path: '/16RaENd5PxeXs6XE4yrnCPjg4Gz.jpg',
      },
      {
        credit_id: '5831cf1b92514162c0027381',
        department: 'Sound',
        gender: 2,
        id: 9349,
        job: 'Supervising Sound Editor',
        name: 'Dane A. Davis',
        profile_path: '/16RaENd5PxeXs6XE4yrnCPjg4Gz.jpg',
      },
      {
        credit_id: '5831d85292514162cb028f00',
        department: 'Sound',
        gender: 2,
        id: 9351,
        job: 'Music Editor',
        name: 'Zigmund Gron',
        profile_path: null,
      },
      {
        credit_id: '5831cfcbc3a3685b9a0278bb',
        department: 'Crew',
        gender: 0,
        id: 9357,
        job: 'Stunt Coordinator',
        name: 'Glenn Boswell',
        profile_path: null,
      },
      {
        credit_id: '5831d03892514162d20277d6',
        department: 'Art',
        gender: 0,
        id: 9420,
        job: 'Assistant Art Director',
        name: 'Jules Cook',
        profile_path: '/qFKAnJ89NrdGaCsbtwAuwMVQ2q9.jpg',
      },
      {
        credit_id: '5831d409c3a3685b93025e33',
        department: 'Visual Effects',
        gender: 0,
        id: 9593,
        job: 'Special Effects Supervisor',
        name: 'Steve Courtley',
        profile_path: null,
      },
      {
        credit_id: '5af40a81925141787a007bd0',
        department: 'Directing',
        gender: 2,
        id: 11266,
        job: 'First Assistant Director',
        name: 'James McTeigue',
        profile_path: null,
      },
      {
        credit_id: '5831d75492514162cb028dda',
        department: 'Sound',
        gender: 2,
        id: 113051,
        job: 'Sound Effects Editor',
        name: 'David Grimaldi',
        profile_path: null,
      },
      {
        credit_id: '5831cd9292514162d8026298',
        department: 'Production',
        gender: 2,
        id: 57526,
        job: 'Co-Producer',
        name: 'Dan Cracchiolo',
        profile_path: null,
      },
      {
        credit_id: '5831d017c3a3685bad025303',
        department: 'Production',
        gender: 0,
        id: 62740,
        job: 'Associate Producer',
        name: 'Richard Mirisch',
        profile_path: null,
      },
      {
        credit_id: '5831cef0c3a3685bad0251b0',
        department: 'Production',
        gender: 1,
        id: 88435,
        job: 'Unit Production Manager',
        name: 'Carol Hughes',
        profile_path: null,
      },
      {
        credit_id: '5831d00bc3a3685b9d028c76',
        department: 'Production',
        gender: 1,
        id: 88435,
        job: 'Associate Producer',
        name: 'Carol Hughes',
        profile_path: null,
      },
      {
        credit_id: '5af406920e0a26396e00791f',
        department: 'Sound',
        gender: 0,
        id: 91093,
        job: 'Dialogue Editor',
        name: 'Charles W. Ritter',
        profile_path: null,
      },
      {
        credit_id: '5831ce5cc3a3685bb0025e2d',
        department: 'Visual Effects',
        gender: 2,
        id: 105108,
        job: 'Visual Effects Supervisor',
        name: 'John Gaeta',
        profile_path: null,
      },
      {
        credit_id: '5831d72dc3a3685b960231d5',
        department: 'Sound',
        gender: 0,
        id: 143915,
        job: 'Sound Effects Editor',
        name: 'Julia Evershade',
        profile_path: null,
      },
      {
        credit_id: '5af40a5892514179fc006bd8',
        department: 'Directing',
        gender: 0,
        id: 1153775,
        job: 'First Assistant Director',
        name: 'Colin Fletcher',
        profile_path: null,
      },
      {
        credit_id: '5831d743c3a3685bad025a34',
        department: 'Sound',
        gender: 0,
        id: 1338152,
        job: 'Sound Effects Editor',
        name: 'Eric Lindemann',
        profile_path: null,
      },
      {
        credit_id: '5831d7e792514162c0027d28',
        department: 'Sound',
        gender: 2,
        id: 1341854,
        job: 'Sound Re-Recording Mixer',
        name: 'David E. Campbell',
        profile_path: null,
      },
      {
        credit_id: '5831d7a592514162cb028e28',
        department: 'Sound',
        gender: 2,
        id: 1341858,
        job: 'Sound Re-Recording Mixer',
        name: 'Gregg Rudloff',
        profile_path: null,
      },
      {
        credit_id: '5831d799c3a3685b96023249',
        department: 'Sound',
        gender: 0,
        id: 1342626,
        job: 'Sound Re-Recording Mixer',
        name: 'John T. Reitz',
        profile_path: null,
      },
      {
        credit_id: '5af40667c3a3682160007799',
        department: 'Sound',
        gender: 1,
        id: 1378225,
        job: 'Dialogue Editor',
        name: 'Susan Dudeck',
        profile_path: null,
      },
      {
        credit_id: '5831d0d592514162c9028394',
        department: 'Art',
        gender: 0,
        id: 1391711,
        job: 'Set Designer',
        name: 'Jacinta Leong',
        profile_path: null,
      },
      {
        credit_id: '5831d041c3a3685b9a02794c',
        department: 'Art',
        gender: 0,
        id: 1392669,
        job: 'Assistant Art Director',
        name: 'Fiona Scott',
        profile_path: null,
      },
      {
        credit_id: '5831d0c892514162d202786e',
        department: 'Art',
        gender: 0,
        id: 1392681,
        job: 'Set Designer',
        name: 'Sarah Light',
        profile_path: null,
      },
      {
        credit_id: '5831d0fa92514162c90283c1',
        department: 'Art',
        gender: 0,
        id: 1392692,
        job: 'Set Designer',
        name: 'Judith Harvey',
        profile_path: null,
      },
      {
        credit_id: '5831d21092514162c302714f',
        department: 'Camera',
        gender: 2,
        id: 1392718,
        job: 'Still Photographer',
        name: 'Jasin Boland',
        profile_path: null,
      },
      {
        credit_id: '5831d1dfc3a3685b93025c29',
        department: 'Camera',
        gender: 0,
        id: 1392719,
        job: 'Camera Operator',
        name: 'Robert Agganis',
        profile_path: null,
      },
      {
        credit_id: '5831d1e5c3a3685b93025c31',
        department: 'Camera',
        gender: 0,
        id: 1392719,
        job: 'Steadicam Operator',
        name: 'Robert Agganis',
        profile_path: null,
      },
      {
        credit_id: '5831d3d7c3a3685b93025e1b',
        department: 'Lighting',
        gender: 0,
        id: 1392722,
        job: 'Gaffer',
        name: 'Reg Garside',
        profile_path: null,
      },
      {
        credit_id: '5831d8e992514162d8026ebe',
        department: 'Production',
        gender: 0,
        id: 1412758,
        job: 'Publicist',
        name: 'Fiona Searson',
        profile_path: null,
      },
      {
        credit_id: '5831d4e2c3a3685ba8027aec',
        department: 'Costume & Make-Up',
        gender: 0,
        id: 1418264,
        job: 'Hairstylist',
        name: 'Cheryl Williams',
        profile_path: null,
      },
      {
        credit_id: '5831d079c3a3685ba8027667',
        department: 'Art',
        gender: 0,
        id: 1418270,
        job: 'Assistant Art Director',
        name: 'Tony Williams',
        profile_path: null,
      },
      {
        credit_id: '5831d719c3a3685bb0026755',
        department: 'Crew',
        gender: 0,
        id: 1434214,
        job: 'Visual Effects Editor',
        name: 'Kate Crossley',
        profile_path: null,
      },
      {
        credit_id: '5831d457c3a3685bb0026404',
        department: 'Visual Effects',
        gender: 2,
        id: 1454936,
        job: 'Special Effects Supervisor',
        name: 'Brian Cox',
        profile_path: null,
      },
      {
        credit_id: '5af406af0e0a26394b006a49',
        department: 'Art',
        gender: 0,
        id: 1470969,
        job: 'Property Master',
        name: 'Lon Lucini',
        profile_path: null,
      },
      {
        credit_id: '5831d186c3a3685ba102ba8f',
        department: 'Directing',
        gender: 0,
        id: 1470982,
        job: 'Script Supervisor',
        name: 'Victoria Sullivan',
        profile_path: null,
      },
      {
        credit_id: '5831d4b6c3a3685ba102be38',
        department: 'Costume & Make-Up',
        gender: 0,
        id: 1536539,
        job: 'Makeup Artist',
        name: 'Deborah Taylor',
        profile_path: null,
      },
      {
        credit_id: '5831d82592514162cf027fc6',
        department: 'Sound',
        gender: 0,
        id: 1537143,
        job: 'Music Editor',
        name: 'Lori L. Eschler',
        profile_path: null,
      },
      {
        credit_id: '5831d8b0c3a3685ba8027f26',
        department: 'Production',
        gender: 0,
        id: 1569080,
        job: 'Location Manager',
        name: 'Peter Lawless',
        profile_path: null,
      },
      {
        credit_id: '5831d15ac3a3685ba802774d',
        department: 'Art',
        gender: 0,
        id: 1575727,
        job: 'Set Decoration',
        name: 'Tim Ferrier',
        profile_path: null,
      },
      {
        credit_id: '5831d1ce92514162cf0278f4',
        department: 'Camera',
        gender: 0,
        id: 1578018,
        job: 'Camera Operator',
        name: 'David Williamson',
        profile_path: null,
      },
      {
        credit_id: '5831d6e8c3a3685b9a028078',
        department: 'Costume & Make-Up',
        gender: 0,
        id: 1619685,
        job: 'Costume Supervisor',
        name: 'Lyn Askew',
        profile_path: null,
      },
      {
        credit_id: '5831d09fc3a3685ba102b98c',
        department: 'Art',
        gender: 0,
        id: 1711544,
        job: 'Art Department Coordinator',
        name: 'Trish Foreman',
        profile_path: null,
      },
      {
        credit_id: '5831d0eb92514162cb028661',
        department: 'Art',
        gender: 0,
        id: 1711545,
        job: 'Set Designer',
        name: 'Godric Cole',
        profile_path: null,
      },
      {
        credit_id: '5831d134c3a3685bb002610c',
        department: 'Art',
        gender: 0,
        id: 1711546,
        job: 'Set Designer',
        name: 'Andrew Powell',
        profile_path: null,
      },
      {
        credit_id: '5831d173c3a3685ba102ba75',
        department: 'Art',
        gender: 0,
        id: 1711547,
        job: 'Set Decoration',
        name: 'Marta McElroy',
        profile_path: null,
      },
      {
        credit_id: '5af402fcc3a368214800a295',
        department: 'Sound',
        gender: 2,
        id: 1711549,
        job: 'Sound Recordist',
        name: 'David Lee',
        profile_path: null,
      },
      {
        credit_id: '5831d372c3a3685b96022e35',
        department: 'Sound',
        gender: 0,
        id: 1711550,
        job: 'Boom Operator',
        name: 'Jack Friedman',
        profile_path: null,
      },
      {
        credit_id: '5831d386c3a3685bb0026365',
        department: 'Sound',
        gender: 0,
        id: 1711551,
        job: 'Boom Operator',
        name: 'Gerry Nucifora',
        profile_path: null,
      },
      {
        credit_id: '5831d474c3a3685bad025731',
        department: 'Crew',
        gender: 0,
        id: 1711553,
        job: 'Special Effects Coordinator',
        name: 'Robina Osbourne',
        profile_path: null,
      },
      {
        credit_id: '5831d8c192514162cf02806d',
        department: 'Production',
        gender: 0,
        id: 1711577,
        job: 'Production Coordinator',
        name: 'Megan Worthy',
        profile_path: null,
      },
    ],
  },
} as Movie

export const person = {
  birthday: '1944-05-14',
  known_for_department: 'Directing',
  deathday: null,
  id: 1,
  name: 'George Lucas',
  also_known_as: [
    'George Walton Lucas Jr. ',
    '乔治·卢卡斯',
    'Джордж Лукас',
    'ジョージ・ルーカス',
    'จอร์จ ลูคัส',
    '조지 루카스',
    'جورج لوكاس',
  ],
  gender: 2,
  biography:
    "George Walton Lucas Jr. (born May 14, 1944) is an American filmmaker and entrepreneur. Lucas is known for creating the Star Wars and Indiana Jones franchises and founding Lucasfilm, LucasArts and Industrial Light & Magic. He served as chairman of Lucasfilm before selling it to The Walt Disney Company in 2012.\n\nAfter graduating from the University of Southern California in 1967, Lucas co-founded American Zoetrope with filmmaker Francis Ford Coppola. Lucas wrote and directed THX 1138 (1971), based on his earlier student short Electronic Labyrinth: THX 1138 4EB, which was a critical success but a financial failure. His next work as a writer-director was the film American Graffiti (1973), inspired by his youth in early 1960s Modesto, California, and produced through the newly founded Lucasfilm. The film was critically and commercially successful, and received five Academy Award nominations including Best Picture.\n\nLucas's next film, the epic space opera Star Wars (1977), had a troubled production but was a surprise hit, becoming the highest-grossing film at the time, winning six Academy Awards and sparking a cultural phenomenon. Lucas produced and co-wrote the sequels The Empire Strikes Back (1980) and Return of the Jedi (1983). With director Steven Spielberg, he created, produced and co-wrote the Indiana Jones films Raiders of the Lost Ark (1981), Temple of Doom (1984), The Last Crusade (1989) and Kingdom of the Crystal Skull (2008). He also produced and wrote a variety of films and television series through Lucasfilm between the 1970s and the 2010s.\n\nIn 1997, Lucas rereleased the Star Wars trilogy as part of a special edition featuring several alterations; home media versions with further changes were released in 2004 and 2011. He returned to directing with a Star Wars prequel trilogy comprising The Phantom Menace (1999), Attack of the Clones (2002), and Revenge of the Sith (2005). He last collaborated on the CGI-animated television series Star Wars: The Clone Wars (2008–2014, 2020), the war film Red Tails (2012), and the CGI film Strange Magic (2015).\n\nLucas is one of history's most financially successful filmmakers and has been nominated for four Academy Awards. His films are among the 100 highest-grossing movies at the North American box office, adjusted for ticket-price inflation. Lucas is considered a significant figure of the 20th-century New Hollywood movement.\n\nDescription above from the Wikipedia article George Lucas, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
  popularity: 13.62,
  place_of_birth: 'Modesto, California, USA',
  profile_path: '/d0ZMdgMz1mVcWWctyF7sbymSlv4.jpg',
  adult: false,
  imdb_id: 'nm0000184',
  homepage: null,
} as Person

export const crew = {
  adult: false,
  gender: 2,
  id: 525,
  known_for_department: 'Directing',
  name: 'Christopher Nolan',
  original_name: 'Christopher Nolan',
  popularity: 13.954,
  profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg',
  credit_id: '5e83abdcd236e60015fd9f9f',
  department: 'Directing',
  job: 'Director, Producer, Writer',
} as Crew

export const cast = {
  cast_id: 34,
  character: 'Thomas A. Anderson / Neo',
  credit_id: '52fe425bc3a36847f80181c1',
  gender: 2,
  id: 6384,
  name: 'Keanu Reeves',
  order: 0,
  profile_path: '/d9HyjGMCt4wgJIOxAGlaYWhKsiN.jpg',
} as Cast

export default {
  genres,
  departments,
  movie,
  person,
  crew,
  cast,
}
